package PlayerGame;


/**
* PlayerGame/_GameServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:09:44 PM CST
*/

public class _GameServiceStub extends org.omg.CORBA.portable.ObjectImpl implements PlayerGame.GameService
{


  // Starts the game session
  public int startGame (int playerID, String sessionToken) throws PlayerGame.NoPlayersAvailableException, PlayerGame.GameTimeoutException, PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startGame", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/NoPlayersAvailableException:1.0"))
                    throw PlayerGame.NoPlayersAvailableExceptionHelper.read ($in);
                else if (_id.equals ("IDL:PlayerGame/GameTimeoutException:1.0"))
                    throw PlayerGame.GameTimeoutExceptionHelper.read ($in);
                else if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startGame (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // startGame


  // Starts the round
  public PlayerGame.Round startRound (int gameID, int playerID, String sessionToken) throws PlayerGame.GameNotFoundException, PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startRound", true);
                $out.write_long (gameID);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                PlayerGame.Round $result = PlayerGame.RoundHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/GameNotFoundException:1.0"))
                    throw PlayerGame.GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startRound (gameID, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // startRound


  // Randomly selects a word it is only called when the round ends
  public String getRandomWord (int gameID, int roundNumber, int playerID, String sessionToken) throws PlayerGame.GameNotFoundException, PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRandomWord", true);
                $out.write_long (gameID);
                $out.write_long (roundNumber);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/GameNotFoundException:1.0"))
                    throw PlayerGame.GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRandomWord (gameID, roundNumber, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRandomWord


  // Processes the playerâ¬"s guessed letter and returns indexes of correctly guessed positions
  public int[] guessLetter (int playerID, String sessionToken, char letter) throws PlayerGame.MaxAttemptsReachedException, PlayerGame.GameNotFoundException, PlayerGame.AlreadyGuessedLetterException, PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("guessLetter", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $out.write_char (letter);
                $in = _invoke ($out);
                int $result[] = PlayerGame.IndexListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/MaxAttemptsReachedException:1.0"))
                    throw PlayerGame.MaxAttemptsReachedExceptionHelper.read ($in);
                else if (_id.equals ("IDL:PlayerGame/GameNotFoundException:1.0"))
                    throw PlayerGame.GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:PlayerGame/AlreadyGuessedLetterException:1.0"))
                    throw PlayerGame.AlreadyGuessedLetterExceptionHelper.read ($in);
                else if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return guessLetter (playerID, sessionToken, letter        );
            } finally {
                _releaseReply ($in);
            }
  } // guessLetter


  // Returns the number of remaining attempts
  public int getRemainingAttempts (int playerID, String sessionToken) throws PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRemainingAttempts", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRemainingAttempts (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRemainingAttempts


  // Uses threads to manage waiting time and round time
  public int getRemainingWaitingTime (int playerID, String sessionToken) throws PlayerGame.GameTimeoutException, PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRemainingWaitingTime", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/GameTimeoutException:1.0"))
                    throw PlayerGame.GameTimeoutExceptionHelper.read ($in);
                else if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRemainingWaitingTime (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRemainingWaitingTime

  public int getRemainingRoundTime (int gameID, int playerID, String sessionToken) throws PlayerGame.GameTimeoutException, PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRemainingRoundTime", true);
                $out.write_long (gameID);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/GameTimeoutException:1.0"))
                    throw PlayerGame.GameTimeoutExceptionHelper.read ($in);
                else if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRemainingRoundTime (gameID, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRemainingRoundTime


  // Game state methods
  public boolean isGameOver (int playerID, String sessionToken) throws PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("isGameOver", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return isGameOver (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // isGameOver

  public String getRoundWinner (int gameID, int playerID, String sessionToken) throws PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRoundWinner", true);
                $out.write_long (gameID);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRoundWinner (gameID, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRoundWinner

  public String getGameWinner (int gameID, int playerID, String sessionToken) throws PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getGameWinner", true);
                $out.write_long (gameID);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getGameWinner (gameID, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getGameWinner


  // Player leaves the game
  public void leaveGame (int playerID, String sessionToken, int gameID) throws PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("leaveGame", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $out.write_long (gameID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                leaveGame (playerID, sessionToken, gameID        );
            } finally {
                _releaseReply ($in);
            }
  } // leaveGame


  // Gets the leaderboard
  public String[] getLeaderboards (int playerID, String sessionToken) throws PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLeaderboards", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result[] = PlayerGame.StringListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLeaderboards (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getLeaderboards

  public int getNumberOfPlayersJoined (int playerID, String sessionToken) throws PlayerGame.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNumberOfPlayersJoined", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PlayerGame/NotLoggedInException:1.0"))
                    throw PlayerGame.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getNumberOfPlayersJoined (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getNumberOfPlayersJoined

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PlayerGame/GameService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "PlayerGame._GameServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GameServiceStub
