package PlayerGame;

/**
* PlayerGame/AlreadyGuessedLetterExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:30 PM CST
*/

public final class AlreadyGuessedLetterExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerGame.AlreadyGuessedLetterException value = null;

  public AlreadyGuessedLetterExceptionHolder ()
  {
  }

  public AlreadyGuessedLetterExceptionHolder (PlayerGame.AlreadyGuessedLetterException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerGame.AlreadyGuessedLetterExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerGame.AlreadyGuessedLetterExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerGame.AlreadyGuessedLetterExceptionHelper.type ();
  }

}
