package PlayerGame;


/**
* PlayerGame/AlreadyLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:03:06 PM CST
*/

public final class AlreadyLoggedInException extends org.omg.CORBA.UserException
{

  public AlreadyLoggedInException ()
  {
    super(AlreadyLoggedInExceptionHelper.id());
  } // ctor


  public AlreadyLoggedInException (String $reason)
  {
    super(AlreadyLoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyLoggedInException
