package PlayerGame;


/**
* PlayerGame/AlreadyGuessedLetterException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:30 PM CST
*/

public final class AlreadyGuessedLetterException extends org.omg.CORBA.UserException
{

  public AlreadyGuessedLetterException ()
  {
    super(AlreadyGuessedLetterExceptionHelper.id());
  } // ctor


  public AlreadyGuessedLetterException (String $reason)
  {
    super(AlreadyGuessedLetterExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyGuessedLetterException
