package PlayerGame;


/**
* PlayerGame/AuthService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:03:06 PM CST
*/


// interface for authentication: login and logout
public interface AuthService extends AuthServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuthService
