package PlayerGame;


/**
* PlayerGame/AuthServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:30 PM CST
*/


// interface for authentication: login and logout
public interface AuthServiceOperations 
{

  // Login returns playerID and sessionToken
  String login (String username, String password, org.omg.CORBA.IntHolder playerID) throws PlayerGame.AuthenticationException, PlayerGame.AlreadyLoggedInException;
  void logout (int playerID, String sessionToken) throws PlayerGame.NotLoggedInException;
} // interface AuthServiceOperations
