package PlayerGame;

/**
* PlayerGame/AuthServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:03:06 PM CST
*/


// interface for authentication: login and logout
public final class AuthServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerGame.AuthService value = null;

  public AuthServiceHolder ()
  {
  }

  public AuthServiceHolder (PlayerGame.AuthService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerGame.AuthServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerGame.AuthServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerGame.AuthServiceHelper.type ();
  }

}
