package PlayerGame;


/**
* PlayerGame/AuthenticationException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:30 PM CST
*/

public final class AuthenticationException extends org.omg.CORBA.UserException
{

  public AuthenticationException ()
  {
    super(AuthenticationExceptionHelper.id());
  } // ctor


  public AuthenticationException (String $reason)
  {
    super(AuthenticationExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AuthenticationException
