package PlayerGame;


/**
* PlayerGame/AuthServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:09:44 PM CST
*/


// interface for authentication: login and logout
public interface AuthServiceOperations 
{

  // Login returns playerID and sessionToken
  String login (String username, String password, org.omg.CORBA.IntHolder playerID) throws PlayerGame.AuthenticationException, PlayerGame.AlreadyLoggedInException;
  void logout (int playerID, String sessionToken) throws PlayerGame.NotLoggedInException;
} // interface AuthServiceOperations
