package PlayerGame;


/**
* PlayerGame/AuthServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:30 PM CST
*/


// interface for authentication: login and logout
abstract public class AuthServiceHelper
{
  private static String  _id = "IDL:PlayerGame/AuthService:1.0";

  public static void insert (org.omg.CORBA.Any a, PlayerGame.AuthService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PlayerGame.AuthService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PlayerGame.AuthServiceHelper.id (), "AuthService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PlayerGame.AuthService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AuthServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PlayerGame.AuthService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PlayerGame.AuthService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PlayerGame.AuthService)
      return (PlayerGame.AuthService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PlayerGame._AuthServiceStub stub = new PlayerGame._AuthServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PlayerGame.AuthService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PlayerGame.AuthService)
      return (PlayerGame.AuthService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PlayerGame._AuthServiceStub stub = new PlayerGame._AuthServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
