package PlayerGame;

/**
* PlayerGame/AuthenticationExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:09:44 PM CST
*/

public final class AuthenticationExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerGame.AuthenticationException value = null;

  public AuthenticationExceptionHolder ()
  {
  }

  public AuthenticationExceptionHolder (PlayerGame.AuthenticationException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerGame.AuthenticationExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerGame.AuthenticationExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerGame.AuthenticationExceptionHelper.type ();
  }

}
