package PlayerGame;


/**
* PlayerGame/AuthService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:30 PM CST
*/


// interface for authentication: login and logout
public interface AuthService extends AuthServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuthService
