package PlayerGame;


/**
* PlayerGame/GameTimeoutException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:03:06 PM CST
*/

public final class GameTimeoutException extends org.omg.CORBA.UserException
{

  public GameTimeoutException ()
  {
    super(GameTimeoutExceptionHelper.id());
  } // ctor


  public GameTimeoutException (String $reason)
  {
    super(GameTimeoutExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class GameTimeoutException
