package PlayerGame;


/**
* PlayerGame/GameServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:03:06 PM CST
*/

public abstract class GameServicePOA extends org.omg.PortableServer.Servant
 implements PlayerGame.GameServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("startGame", new java.lang.Integer (0));
    _methods.put ("startRound", new java.lang.Integer (1));
    _methods.put ("getRandomWord", new java.lang.Integer (2));
    _methods.put ("guessLetter", new java.lang.Integer (3));
    _methods.put ("getRemainingAttempts", new java.lang.Integer (4));
    _methods.put ("getRemainingWaitingTime", new java.lang.Integer (5));
    _methods.put ("getRemainingRoundTime", new java.lang.Integer (6));
    _methods.put ("isGameOver", new java.lang.Integer (7));
    _methods.put ("getRoundWinner", new java.lang.Integer (8));
    _methods.put ("getGameWinner", new java.lang.Integer (9));
    _methods.put ("leaveGame", new java.lang.Integer (10));
    _methods.put ("getLeaderboards", new java.lang.Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Starts the game session
       case 0:  // PlayerGame/GameService/startGame
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           int $result = (int)0;
           $result = this.startGame (playerID, sessionToken);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (PlayerGame.NoPlayersAvailableException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NoPlayersAvailableExceptionHelper.write (out, $ex);
         } catch (PlayerGame.GameTimeoutException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.GameTimeoutExceptionHelper.write (out, $ex);
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Starts the round
       case 1:  // PlayerGame/GameService/startRound
       {
         try {
           int gameID = in.read_long ();
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           PlayerGame.Round $result = null;
           $result = this.startRound (gameID, playerID, sessionToken);
           out = $rh.createReply();
           PlayerGame.RoundHelper.write (out, $result);
         } catch (PlayerGame.GameNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.GameNotFoundExceptionHelper.write (out, $ex);
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Randomly selects a word it is only called when the round ends
       case 2:  // PlayerGame/GameService/getRandomWord
       {
         try {
           int gameID = in.read_long ();
           int roundNumber = in.read_long ();
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           String $result = null;
           $result = this.getRandomWord (gameID, roundNumber, playerID, sessionToken);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (PlayerGame.GameNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.GameNotFoundExceptionHelper.write (out, $ex);
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Processes the playerâ¬"s guessed letter and returns indexes of correctly guessed positions
       case 3:  // PlayerGame/GameService/guessLetter
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           char letter = in.read_char ();
           int $result[] = null;
           $result = this.guessLetter (playerID, sessionToken, letter);
           out = $rh.createReply();
           PlayerGame.IndexListHelper.write (out, $result);
         } catch (PlayerGame.MaxAttemptsReachedException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.MaxAttemptsReachedExceptionHelper.write (out, $ex);
         } catch (PlayerGame.GameNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.GameNotFoundExceptionHelper.write (out, $ex);
         } catch (PlayerGame.AlreadyGuessedLetterException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.AlreadyGuessedLetterExceptionHelper.write (out, $ex);
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Returns the number of remaining attempts
       case 4:  // PlayerGame/GameService/getRemainingAttempts
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           int $result = (int)0;
           $result = this.getRemainingAttempts (playerID, sessionToken);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Uses threads to manage waiting time and round time
       case 5:  // PlayerGame/GameService/getRemainingWaitingTime
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           int $result = (int)0;
           $result = this.getRemainingWaitingTime (playerID, sessionToken);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (PlayerGame.GameTimeoutException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.GameTimeoutExceptionHelper.write (out, $ex);
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 6:  // PlayerGame/GameService/getRemainingRoundTime
       {
         try {
           int gameID = in.read_long ();
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           int $result = (int)0;
           $result = this.getRemainingRoundTime (gameID, playerID, sessionToken);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (PlayerGame.GameTimeoutException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.GameTimeoutExceptionHelper.write (out, $ex);
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Game state methods
       case 7:  // PlayerGame/GameService/isGameOver
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           boolean $result = false;
           $result = this.isGameOver (playerID, sessionToken);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // PlayerGame/GameService/getRoundWinner
       {
         try {
           int gameID = in.read_long ();
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           String $result = null;
           $result = this.getRoundWinner (gameID, playerID, sessionToken);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 9:  // PlayerGame/GameService/getGameWinner
       {
         try {
           int gameID = in.read_long ();
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           String $result = null;
           $result = this.getGameWinner (gameID, playerID, sessionToken);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Player leaves the game
       case 10:  // PlayerGame/GameService/leaveGame
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           int gameID = in.read_long ();
           this.leaveGame (playerID, sessionToken, gameID);
           out = $rh.createReply();
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Gets the leaderboard
       case 11:  // PlayerGame/GameService/getLeaderboards
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           String $result[] = null;
           $result = this.getLeaderboards (playerID, sessionToken);
           out = $rh.createReply();
           PlayerGame.StringListHelper.write (out, $result);
         } catch (PlayerGame.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerGame.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PlayerGame/GameService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameService _this() 
  {
    return GameServiceHelper.narrow(
    super._this_object());
  }

  public GameService _this(org.omg.CORBA.ORB orb) 
  {
    return GameServiceHelper.narrow(
    super._this_object(orb));
  }


} // class GameServicePOA
