package PlayerGame;

/**
* PlayerGame/GameServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:03:06 PM CST
*/

public final class GameServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerGame.GameService value = null;

  public GameServiceHolder ()
  {
  }

  public GameServiceHolder (PlayerGame.GameService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerGame.GameServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerGame.GameServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerGame.GameServiceHelper.type ();
  }

}
