package PlayerGame;


/**
* PlayerGame/GameNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:30 PM CST
*/

public final class GameNotFoundException extends org.omg.CORBA.UserException
{

  public GameNotFoundException ()
  {
    super(GameNotFoundExceptionHelper.id());
  } // ctor


  public GameNotFoundException (String $reason)
  {
    super(GameNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class GameNotFoundException
