package PlayerGame;


/**
* PlayerGame/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:03:06 PM CST
*/

public interface GameServiceOperations 
{

  // Starts the game session
  int startGame (int playerID, String sessionToken) throws PlayerGame.NoPlayersAvailableException, PlayerGame.GameTimeoutException, PlayerGame.NotLoggedInException;

  // Starts the round
  PlayerGame.Round startRound (int gameID, int playerID, String sessionToken) throws PlayerGame.GameNotFoundException, PlayerGame.NotLoggedInException;

  // Randomly selects a word it is only called when the round ends
  String getRandomWord (int gameID, int roundNumber, int playerID, String sessionToken) throws PlayerGame.GameNotFoundException, PlayerGame.NotLoggedInException;

  // Processes the playerâ¬"s guessed letter and returns indexes of correctly guessed positions
  int[] guessLetter (int playerID, String sessionToken, char letter) throws PlayerGame.MaxAttemptsReachedException, PlayerGame.GameNotFoundException, PlayerGame.AlreadyGuessedLetterException, PlayerGame.NotLoggedInException;

  // Returns the number of remaining attempts
  int getRemainingAttempts (int playerID, String sessionToken) throws PlayerGame.NotLoggedInException;

  // Uses threads to manage waiting time and round time
  int getRemainingWaitingTime (int playerID, String sessionToken) throws PlayerGame.GameTimeoutException, PlayerGame.NotLoggedInException;
  int getRemainingRoundTime (int gameID, int playerID, String sessionToken) throws PlayerGame.GameTimeoutException, PlayerGame.NotLoggedInException;

  // Game state methods
  boolean isGameOver (int playerID, String sessionToken) throws PlayerGame.NotLoggedInException;
  String getRoundWinner (int gameID, int playerID, String sessionToken) throws PlayerGame.NotLoggedInException;
  String getGameWinner (int gameID, int playerID, String sessionToken) throws PlayerGame.NotLoggedInException;

  // Player leaves the game
  void leaveGame (int playerID, String sessionToken, int gameID) throws PlayerGame.NotLoggedInException;

  // Gets the leaderboard
  String[] getLeaderboards (int playerID, String sessionToken) throws PlayerGame.NotLoggedInException;
} // interface GameServiceOperations
