package PlayerGame;


/**
* PlayerGame/IndexListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:29 PM CST
*/

public final class IndexListHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public IndexListHolder ()
  {
  }

  public IndexListHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerGame.IndexListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerGame.IndexListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerGame.IndexListHelper.type ();
  }

}
