package PlayerGame;


/**
* PlayerGame/MaxAttemptsReachedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:30 PM CST
*/

public final class MaxAttemptsReachedException extends org.omg.CORBA.UserException
{

  public MaxAttemptsReachedException ()
  {
    super(MaxAttemptsReachedExceptionHelper.id());
  } // ctor


  public MaxAttemptsReachedException (String $reason)
  {
    super(MaxAttemptsReachedExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class MaxAttemptsReachedException
