package PlayerGame;

/**
* PlayerGame/MaxAttemptsReachedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:30 PM CST
*/

public final class MaxAttemptsReachedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerGame.MaxAttemptsReachedException value = null;

  public MaxAttemptsReachedExceptionHolder ()
  {
  }

  public MaxAttemptsReachedExceptionHolder (PlayerGame.MaxAttemptsReachedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerGame.MaxAttemptsReachedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerGame.MaxAttemptsReachedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerGame.MaxAttemptsReachedExceptionHelper.type ();
  }

}
