package PlayerGame;

/**
* PlayerGame/NoPlayersAvailableExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:03:06 PM CST
*/

public final class NoPlayersAvailableExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerGame.NoPlayersAvailableException value = null;

  public NoPlayersAvailableExceptionHolder ()
  {
  }

  public NoPlayersAvailableExceptionHolder (PlayerGame.NoPlayersAvailableException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerGame.NoPlayersAvailableExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerGame.NoPlayersAvailableExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerGame.NoPlayersAvailableExceptionHelper.type ();
  }

}
