package PlayerGame;


/**
* PlayerGame/NoPlayersAvailableException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:30 PM CST
*/

public final class NoPlayersAvailableException extends org.omg.CORBA.UserException
{

  public NoPlayersAvailableException ()
  {
    super(NoPlayersAvailableExceptionHelper.id());
  } // ctor


  public NoPlayersAvailableException (String $reason)
  {
    super(NoPlayersAvailableExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NoPlayersAvailableException
