package PlayerGame;


/**
* PlayerGame/NotLoggedInExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:09:44 PM CST
*/

abstract public class NotLoggedInExceptionHelper
{
  private static String  _id = "IDL:PlayerGame/NotLoggedInException:1.0";

  public static void insert (org.omg.CORBA.Any a, PlayerGame.NotLoggedInException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PlayerGame.NotLoggedInException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [0];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (PlayerGame.NotLoggedInExceptionHelper.id (), "NotLoggedInException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PlayerGame.NotLoggedInException read (org.omg.CORBA.portable.InputStream istream)
  {
    PlayerGame.NotLoggedInException value = new PlayerGame.NotLoggedInException ();
    // read and discard the repository ID
    istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PlayerGame.NotLoggedInException value)
  {
    // write the repository ID
    ostream.write_string (id ());
  }

}
