package PlayerGame;


/**
* PlayerGame/NotLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerGame.idl
* Sunday, April 13, 2025 11:03:30 PM CST
*/

public final class NotLoggedInException extends org.omg.CORBA.UserException
{

  public NotLoggedInException ()
  {
    super(NotLoggedInExceptionHelper.id());
  } // ctor


  public NotLoggedInException (String $reason)
  {
    super(NotLoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NotLoggedInException
