package PlayerGame;

/**
* PlayerGame/RoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerGame.idl
* Monday, April 21, 2025 9:09:44 PM CST
*/

public final class RoundHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerGame.Round value = null;

  public RoundHolder ()
  {
  }

  public RoundHolder (PlayerGame.Round initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerGame.RoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerGame.RoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerGame.RoundHelper.type ();
  }

}
