package GameIDL;


/**
* GameIDL/_GameServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 7, 2025 8:53:23 AM CST
*/


//
public class _GameServiceStub extends org.omg.CORBA.portable.ObjectImpl implements GameIDL.GameService
{


  // â¬â¬â¬ Player Authentication & Info â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  public String getDisplayName (int playerID, String sessionToken) throws GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getDisplayName", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getDisplayName (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getDisplayName

  public String[] getLeaderboards (int playerID, String sessionToken) throws GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLeaderboards", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result[] = GameIDL.StringListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLeaderboards (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getLeaderboards


  // â¬â¬â¬ Settings Retrieval â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  public void getSetting (String key, org.omg.CORBA.StringHolder value, String sessionToken) throws GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getSetting", true);
                $out.write_string (key);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                value.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getSetting (key, value, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getSetting


  // â¬â¬â¬ Lobby Management â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  public String joinLobby (int playerID, String sessionToken) throws GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("joinLobby", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return joinLobby (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // joinLobby

  public void leaveLobby (int playerID, String gameToken, String sessionToken) throws GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("leaveLobby", true);
                $out.write_long (playerID);
                $out.write_string (gameToken);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                leaveLobby (playerID, gameToken, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // leaveLobby


  // â¬â¬â¬ Waiting-room callback registration â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  public void registerWaitingRoomCallback (int playerID, String gameToken, String sessionToken, PlayerCallBackIDL.WaitingRoomGameCallbackService cb) throws GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerWaitingRoomCallback", true);
                $out.write_long (playerID);
                $out.write_string (gameToken);
                $out.write_string (sessionToken);
                PlayerCallBackIDL.WaitingRoomGameCallbackServiceHelper.write ($out, cb);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerWaitingRoomCallback (playerID, gameToken, sessionToken, cb        );
            } finally {
                _releaseReply ($in);
            }
  } // registerWaitingRoomCallback

  public String getLobbyStatus (String sessionToken) throws GameIDL.NotLoggedInException, GameIDL.GameTimeOutException, GameIDL.NotEnoughPlayersException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLobbyStatus", true);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/GameTimeOutException:1.0"))
                    throw GameIDL.GameTimeOutExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/NotEnoughPlayersException:1.0"))
                    throw GameIDL.NotEnoughPlayersExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLobbyStatus (sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getLobbyStatus

  public int getNumberOfPlayersJoined (int playerID, String sessionToken) throws GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNumberOfPlayersJoined", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getNumberOfPlayersJoined (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getNumberOfPlayersJoined

  public int startGame (int playerID, String sessionToken) throws GameIDL.NotEnoughPlayersException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startGame", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotEnoughPlayersException:1.0"))
                    throw GameIDL.NotEnoughPlayersExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startGame (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // startGame


  // â¬â¬â¬ Register the client's callback servant here â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  public void registerCallBack (int playerID, String gameToken, String sessionToken, PlayerCallBackIDL.GameCallBackService cb) throws GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerCallBack", true);
                $out.write_long (playerID);
                $out.write_string (gameToken);
                $out.write_string (sessionToken);
                PlayerCallBackIDL.GameCallBackServiceHelper.write ($out, cb);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerCallBack (playerID, gameToken, sessionToken, cb        );
            } finally {
                _releaseReply ($in);
            }
  } // registerCallBack


  // â¬â¬â¬ Game and Round Management â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  public int startRound (String gameToken, int roundNumber, int playerID, String sessionToken) throws GameIDL.GameNotFoundException, GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startRound", true);
                $out.write_string (gameToken);
                $out.write_long (roundNumber);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/GameNotFoundException:1.0"))
                    throw GameIDL.GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startRound (gameToken, roundNumber, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // startRound

  public String getRandomWord (String gameToken, int roundNumber, int playerID, String sessionToken) throws GameIDL.GameNotFoundException, GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRandomWord", true);
                $out.write_string (gameToken);
                $out.write_long (roundNumber);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/GameNotFoundException:1.0"))
                    throw GameIDL.GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRandomWord (gameToken, roundNumber, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRandomWord


  // â¬â¬â¬ Letter Guessing â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  public int[] guessLetter (String gameToken, int playerID, String sessionToken, char letter) throws GameIDL.MaxAttemptsReachedException, GameIDL.GameNotFoundException, GameIDL.AlreadyGuessedLetterException, GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("guessLetter", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $out.write_char (letter);
                $in = _invoke ($out);
                int $result[] = GameIDL.IndexListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/MaxAttemptsReachedException:1.0"))
                    throw GameIDL.MaxAttemptsReachedExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/GameNotFoundException:1.0"))
                    throw GameIDL.GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/AlreadyGuessedLetterException:1.0"))
                    throw GameIDL.AlreadyGuessedLetterExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return guessLetter (gameToken, playerID, sessionToken, letter        );
            } finally {
                _releaseReply ($in);
            }
  } // guessLetter


  // â¬â¬â¬ Game and Round Results â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  public String getRoundWinner (String gameToken, int playerID, String sessionToken) throws GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRoundWinner", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRoundWinner (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRoundWinner

  public String getGameWinner (String gameToken, int playerID, String sessionToken) throws GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getGameWinner", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getGameWinner (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getGameWinner

  public int getPlayerWins (String gameToken, int playerID, String sessionToken) throws GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPlayerWins", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPlayerWins (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getPlayerWins

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GameIDL/GameService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "GameIDL._GameServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GameServiceStub
