package GameIDL;

/**
* GameIDL/AlreadyGuessedLetterExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 7, 2025 8:53:23 AM CST
*/

public final class AlreadyGuessedLetterExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameIDL.AlreadyGuessedLetterException value = null;

  public AlreadyGuessedLetterExceptionHolder ()
  {
  }

  public AlreadyGuessedLetterExceptionHolder (GameIDL.AlreadyGuessedLetterException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameIDL.AlreadyGuessedLetterExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameIDL.AlreadyGuessedLetterExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameIDL.AlreadyGuessedLetterExceptionHelper.type ();
  }

}
