package GameIDL;


/**
* GameIDL/AlreadyLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 7, 2025 8:53:23 AM CST
*/


//
public final class AlreadyLoggedInException extends org.omg.CORBA.UserException
{

  public AlreadyLoggedInException ()
  {
    super(AlreadyLoggedInExceptionHelper.id());
  } // ctor


  public AlreadyLoggedInException (String $reason)
  {
    super(AlreadyLoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyLoggedInException
