package GameIDL;


/**
* GameIDL/AlreadyGuessedLetterException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 14, 2025 9:07:31 PM SGT
*/

public final class AlreadyGuessedLetterException extends org.omg.CORBA.UserException
{

  public AlreadyGuessedLetterException ()
  {
    super(AlreadyGuessedLetterExceptionHelper.id());
  } // ctor


  public AlreadyGuessedLetterException (String $reason)
  {
    super(AlreadyGuessedLetterExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyGuessedLetterException
