package GameIDL;


/**
* GameIDL/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 7, 2025 8:53:23 AM CST
*/


//
public interface GameServiceOperations 
{

  // â¬â¬â¬ Player Authentication & Info â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  String getDisplayName (int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
  String[] getLeaderboards (int playerID, String sessionToken) throws GameIDL.NotLoggedInException;

  // â¬â¬â¬ Settings Retrieval â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  void getSetting (String key, org.omg.CORBA.StringHolder value, String sessionToken) throws GameIDL.NotLoggedInException;

  // â¬â¬â¬ Lobby Management â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  String joinLobby (int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
  void leaveLobby (int playerID, String gameToken, String sessionToken) throws GameIDL.NotLoggedInException;

  // â¬â¬â¬ Waiting-room callback registration â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  void registerWaitingRoomCallback (int playerID, String gameToken, String sessionToken, PlayerCallBackIDL.WaitingRoomGameCallbackService cb) throws GameIDL.NotLoggedInException;
  String getLobbyStatus (String sessionToken) throws GameIDL.NotLoggedInException, GameIDL.GameTimeOutException, GameIDL.NotEnoughPlayersException;
  int getNumberOfPlayersJoined (int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
  int startGame (int playerID, String sessionToken) throws GameIDL.NotEnoughPlayersException;

  // â¬â¬â¬ Register the client's callback servant here â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  void registerCallBack (int playerID, String gameToken, String sessionToken, PlayerCallBackIDL.GameCallBackService cb) throws GameIDL.NotLoggedInException;

  // â¬â¬â¬ Game and Round Management â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  int startRound (String gameToken, int roundNumber, int playerID, String sessionToken) throws GameIDL.GameNotFoundException, GameIDL.NotLoggedInException;
  String getRandomWord (String gameToken, int roundNumber, int playerID, String sessionToken) throws GameIDL.GameNotFoundException, GameIDL.NotLoggedInException;

  // â¬â¬â¬ Letter Guessing â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  int[] guessLetter (String gameToken, int playerID, String sessionToken, char letter) throws GameIDL.MaxAttemptsReachedException, GameIDL.GameNotFoundException, GameIDL.AlreadyGuessedLetterException, GameIDL.NotLoggedInException;

  // â¬â¬â¬ Game and Round Results â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
  String getRoundWinner (String gameToken, int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
  String getGameWinner (String gameToken, int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
  int getPlayerWins (String gameToken, int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
} // interface GameServiceOperations
