package GameIDL;


/**
* GameIDL/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 14, 2025 9:07:31 PM SGT
*/


//
public interface GameServiceOperations 
{

  // ������ Player Authentication & Info ��������������������������������������������������������������
  String getDisplayName (int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
  String[] getLeaderboards (int playerID, String sessionToken) throws GameIDL.NotLoggedInException;

  // ������ Settings Retrieval ����������������������������������������������������������������������������������
  void getSetting (String key, org.omg.CORBA.StringHolder value, String sessionToken) throws GameIDL.NotLoggedInException;

  // ������ Lobby Management ��������������������������������������������������������������������������������������
  String joinLobby (int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
  void leaveLobby (int playerID, String gameToken, String sessionToken) throws GameIDL.NotLoggedInException;

  // ������ Waiting-room callback registration ��������������������������������������������������
  void registerWaitingRoomCallback (int playerID, String gameToken, String sessionToken, PlayerCallBackIDL.WaitingRoomGameCallbackService cb) throws GameIDL.NotLoggedInException;
  String getLobbyStatus (String sessionToken) throws GameIDL.NotLoggedInException, GameIDL.GameTimeOutException, GameIDL.NotEnoughPlayersException;
  int getNumberOfPlayersJoined (int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
  int startGame (int playerID, String sessionToken) throws GameIDL.NotEnoughPlayersException;

  // ������ Register the client's callback servant here ��������������������������������
  void registerCallBack (int playerID, String gameToken, String sessionToken, PlayerCallBackIDL.GameCallBackService cb) throws GameIDL.NotLoggedInException;

  // ������ Game and Round Management ��������������������������������������������������������������������
  int startRound (String gameToken, int roundNumber, int playerID, String sessionToken) throws GameIDL.GameNotFoundException, GameIDL.NotLoggedInException;
  String getRandomWord (String gameToken, int roundNumber, int playerID, String sessionToken) throws GameIDL.GameNotFoundException, GameIDL.NotLoggedInException;

  // ������ Letter Guessing ��������������������������������������������������������������������������������������
  int[] guessLetter (String gameToken, int playerID, String sessionToken, char letter, int guessTime) throws GameIDL.MaxAttemptsReachedException, GameIDL.GameNotFoundException, GameIDL.AlreadyGuessedLetterException, GameIDL.NotLoggedInException;

  // ������ Game and Round Results ����������������������������������������������������������������������
  String getRoundWinner (String gameToken, int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
  String getGameWinner (String gameToken, int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
  int getPlayerWins (String gameToken, int playerID, String sessionToken) throws GameIDL.NotLoggedInException;
} // interface GameServiceOperations
