package GameIDL;


/**
* GameIDL/GameServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 14, 2025 9:07:31 PM SGT
*/


//
public abstract class GameServicePOA extends org.omg.PortableServer.Servant
 implements GameIDL.GameServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getDisplayName", new java.lang.Integer (0));
    _methods.put ("getLeaderboards", new java.lang.Integer (1));
    _methods.put ("getSetting", new java.lang.Integer (2));
    _methods.put ("joinLobby", new java.lang.Integer (3));
    _methods.put ("leaveLobby", new java.lang.Integer (4));
    _methods.put ("registerWaitingRoomCallback", new java.lang.Integer (5));
    _methods.put ("getLobbyStatus", new java.lang.Integer (6));
    _methods.put ("getNumberOfPlayersJoined", new java.lang.Integer (7));
    _methods.put ("startGame", new java.lang.Integer (8));
    _methods.put ("registerCallBack", new java.lang.Integer (9));
    _methods.put ("startRound", new java.lang.Integer (10));
    _methods.put ("getRandomWord", new java.lang.Integer (11));
    _methods.put ("guessLetter", new java.lang.Integer (12));
    _methods.put ("getRoundWinner", new java.lang.Integer (13));
    _methods.put ("getGameWinner", new java.lang.Integer (14));
    _methods.put ("getPlayerWins", new java.lang.Integer (15));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // â¬â¬â¬ Player Authentication & Info â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
       case 0:  // GameIDL/GameService/getDisplayName
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           String $result = null;
           $result = this.getDisplayName (playerID, sessionToken);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // GameIDL/GameService/getLeaderboards
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           String $result[] = null;
           $result = this.getLeaderboards (playerID, sessionToken);
           out = $rh.createReply();
           GameIDL.StringListHelper.write (out, $result);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // â¬â¬â¬ Settings Retrieval â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
       case 2:  // GameIDL/GameService/getSetting
       {
         try {
           String key = in.read_string ();
           org.omg.CORBA.StringHolder value = new org.omg.CORBA.StringHolder ();
           String sessionToken = in.read_string ();
           this.getSetting (key, value, sessionToken);
           out = $rh.createReply();
           out.write_string (value.value);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // â¬â¬â¬ Lobby Management â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
       case 3:  // GameIDL/GameService/joinLobby
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           String $result = null;
           $result = this.joinLobby (playerID, sessionToken);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // GameIDL/GameService/leaveLobby
       {
         try {
           int playerID = in.read_long ();
           String gameToken = in.read_string ();
           String sessionToken = in.read_string ();
           this.leaveLobby (playerID, gameToken, sessionToken);
           out = $rh.createReply();
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // â¬â¬â¬ Waiting-room callback registration â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
       case 5:  // GameIDL/GameService/registerWaitingRoomCallback
       {
         try {
           int playerID = in.read_long ();
           String gameToken = in.read_string ();
           String sessionToken = in.read_string ();
           PlayerCallBackIDL.WaitingRoomGameCallbackService cb = PlayerCallBackIDL.WaitingRoomGameCallbackServiceHelper.read (in);
           this.registerWaitingRoomCallback (playerID, gameToken, sessionToken, cb);
           out = $rh.createReply();
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 6:  // GameIDL/GameService/getLobbyStatus
       {
         try {
           String sessionToken = in.read_string ();
           String $result = null;
           $result = this.getLobbyStatus (sessionToken);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         } catch (GameIDL.GameTimeOutException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.GameTimeOutExceptionHelper.write (out, $ex);
         } catch (GameIDL.NotEnoughPlayersException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotEnoughPlayersExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 7:  // GameIDL/GameService/getNumberOfPlayersJoined
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           int $result = (int)0;
           $result = this.getNumberOfPlayersJoined (playerID, sessionToken);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // GameIDL/GameService/startGame
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           int $result = (int)0;
           $result = this.startGame (playerID, sessionToken);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (GameIDL.NotEnoughPlayersException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotEnoughPlayersExceptionHelper.write (out, $ex);
         }
         break;
       }


  // â¬â¬â¬ Register the client's callback servant here â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
       case 9:  // GameIDL/GameService/registerCallBack
       {
         try {
           int playerID = in.read_long ();
           String gameToken = in.read_string ();
           String sessionToken = in.read_string ();
           PlayerCallBackIDL.GameCallBackService cb = PlayerCallBackIDL.GameCallBackServiceHelper.read (in);
           this.registerCallBack (playerID, gameToken, sessionToken, cb);
           out = $rh.createReply();
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // â¬â¬â¬ Game and Round Management â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
       case 10:  // GameIDL/GameService/startRound
       {
         try {
           String gameToken = in.read_string ();
           int roundNumber = in.read_long ();
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           int $result = (int)0;
           $result = this.startRound (gameToken, roundNumber, playerID, sessionToken);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (GameIDL.GameNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.GameNotFoundExceptionHelper.write (out, $ex);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 11:  // GameIDL/GameService/getRandomWord
       {
         try {
           String gameToken = in.read_string ();
           int roundNumber = in.read_long ();
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           String $result = null;
           $result = this.getRandomWord (gameToken, roundNumber, playerID, sessionToken);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (GameIDL.GameNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.GameNotFoundExceptionHelper.write (out, $ex);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // â¬â¬â¬ Letter Guessing â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
       case 12:  // GameIDL/GameService/guessLetter
       {
         try {
           String gameToken = in.read_string ();
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           char letter = in.read_char ();
           int guessTime = in.read_long ();
           int $result[] = null;
           $result = this.guessLetter (gameToken, playerID, sessionToken, letter, guessTime);
           out = $rh.createReply();
           GameIDL.IndexListHelper.write (out, $result);
         } catch (GameIDL.MaxAttemptsReachedException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.MaxAttemptsReachedExceptionHelper.write (out, $ex);
         } catch (GameIDL.GameNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.GameNotFoundExceptionHelper.write (out, $ex);
         } catch (GameIDL.AlreadyGuessedLetterException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.AlreadyGuessedLetterExceptionHelper.write (out, $ex);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // â¬â¬â¬ Game and Round Results â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬â¬
       case 13:  // GameIDL/GameService/getRoundWinner
       {
         try {
           String gameToken = in.read_string ();
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           String $result = null;
           $result = this.getRoundWinner (gameToken, playerID, sessionToken);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 14:  // GameIDL/GameService/getGameWinner
       {
         try {
           String gameToken = in.read_string ();
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           String $result = null;
           $result = this.getGameWinner (gameToken, playerID, sessionToken);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 15:  // GameIDL/GameService/getPlayerWins
       {
         try {
           String gameToken = in.read_string ();
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           int $result = (int)0;
           $result = this.getPlayerWins (gameToken, playerID, sessionToken);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (GameIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GameIDL/GameService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameService _this() 
  {
    return GameServiceHelper.narrow(
    super._this_object());
  }

  public GameService _this(org.omg.CORBA.ORB orb) 
  {
    return GameServiceHelper.narrow(
    super._this_object(orb));
  }


} // class GameServicePOA
