package GameIDL;


/**
* GameIDL/GameTimeOutException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 14, 2025 9:07:31 PM SGT
*/

public final class GameTimeOutException extends org.omg.CORBA.UserException
{

  public GameTimeOutException ()
  {
    super(GameTimeOutExceptionHelper.id());
  } // ctor


  public GameTimeOutException (String $reason)
  {
    super(GameTimeOutExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class GameTimeOutException
