package GameIDL;

/**
* GameIDL/GameTimeOutExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 7, 2025 8:53:23 AM CST
*/

public final class GameTimeOutExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameIDL.GameTimeOutException value = null;

  public GameTimeOutExceptionHolder ()
  {
  }

  public GameTimeOutExceptionHolder (GameIDL.GameTimeOutException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameIDL.GameTimeOutExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameIDL.GameTimeOutExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameIDL.GameTimeOutExceptionHelper.type ();
  }

}
