package GameIDL;

/**
* GameIDL/GameServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 7, 2025 8:53:23 AM CST
*/


//
public final class GameServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public GameIDL.GameService value = null;

  public GameServiceHolder ()
  {
  }

  public GameServiceHolder (GameIDL.GameService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameIDL.GameServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameIDL.GameServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameIDL.GameServiceHelper.type ();
  }

}
