package GameIDL;


/**
* GameIDL/MaxAttemptsReachedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 7, 2025 8:53:23 AM CST
*/

public final class MaxAttemptsReachedException extends org.omg.CORBA.UserException
{

  public MaxAttemptsReachedException ()
  {
    super(MaxAttemptsReachedExceptionHelper.id());
  } // ctor


  public MaxAttemptsReachedException (String $reason)
  {
    super(MaxAttemptsReachedExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class MaxAttemptsReachedException
