package GameIDL;

/**
* GameIDL/MaxAttemptsReachedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Wednesday, May 7, 2025 8:53:23 AM CST
*/

public final class MaxAttemptsReachedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameIDL.MaxAttemptsReachedException value = null;

  public MaxAttemptsReachedExceptionHolder ()
  {
  }

  public MaxAttemptsReachedExceptionHolder (GameIDL.MaxAttemptsReachedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameIDL.MaxAttemptsReachedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameIDL.MaxAttemptsReachedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameIDL.MaxAttemptsReachedExceptionHelper.type ();
  }

}
