package IDL_Files.AdminIDL;


/**
* IDL_Files.AdminIDL/AccountNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Saturday, April 26, 2025 2:02:36 PM SGT
*/

public final class AccountNotFoundException extends org.omg.CORBA.UserException
{

  public AccountNotFoundException ()
  {
    super(AccountNotFoundExceptionHelper.id());
  } // ctor


  public AccountNotFoundException (String $reason)
  {
    super(AccountNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccountNotFoundException
