package IDL_Files.AdminIDL;


/**
* IDL_Files.AdminIDL/AccountCurrentlyActiveException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Saturday, April 26, 2025 2:02:36 PM SGT
*/

public final class AccountCurrentlyActiveException extends org.omg.CORBA.UserException
{

  public AccountCurrentlyActiveException ()
  {
    super(AccountCurrentlyActiveExceptionHelper.id());
  } // ctor


  public AccountCurrentlyActiveException (String $reason)
  {
    super(AccountCurrentlyActiveExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccountCurrentlyActiveException
