package IDL_Files.AdminIDL;

/**
* IDL_Files.AdminIDL/AdminServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Saturday, April 26, 2025 2:02:36 PM SGT
*/

public final class AdminServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public IDL_Files.AdminIDL.AdminService value = null;

  public AdminServiceHolder ()
  {
  }

  public AdminServiceHolder (IDL_Files.AdminIDL.AdminService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL_Files.AdminIDL.AdminServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL_Files.AdminIDL.AdminServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL_Files.AdminIDL.AdminServiceHelper.type ();
  }

}
