package IDL_Files.AdminIDL;


/**
* IDL_Files.AdminIDL/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Saturday, April 26, 2025 2:02:36 PM SGT
*/

public interface AdminServiceOperations 
{

  // Create a new player account
  void createPlayer (String username, String password, String sessionToken, int adminID) throws IDL_Files.AdminIDL.AccountExistsException, IDL_Files.AdminIDL.NotLoggedInException;

  // Modify existing player's password
  void modifyPlayer (int playerID, String newPassword, String sessionToken, int adminID) throws IDL_Files.AdminIDL.AccountNotFoundException, IDL_Files.AdminIDL.ExistingPasswordException, IDL_Files.AdminIDL.NotLoggedInException;

  // Delete player account
  void deletePlayer (int playerID, String sessionToken, int adminID) throws IDL_Files.AdminIDL.AccountNotFoundException, IDL_Files.AdminIDL.AccountCurrentlyActiveException, IDL_Files.AdminIDL.NotLoggedInException;

  // Search for a player by username
  String searchPlayer (String username, String sessionToken, int adminID) throws IDL_Files.AdminIDL.NotLoggedInException, IDL_Files.AdminIDL.PlayerNotFoundException;

  // Change waiting time before game starts
  void modifyWaitingTime (int waitTime, String sessionToken, int adminID) throws IDL_Files.AdminIDL.NotLoggedInException;

  // Change time duration for each round
  void modifyRoundDuration (int roundTime, String sessionToken, int adminID) throws IDL_Files.AdminIDL.NotLoggedInException;
} // interface AdminServiceOperations
