package IDL_Files.AdminIDL;


/**
* IDL_Files.AdminIDL/AdminServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Saturday, April 26, 2025 2:02:36 PM SGT
*/

public abstract class AdminServicePOA extends org.omg.PortableServer.Servant
 implements IDL_Files.AdminIDL.AdminServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createPlayer", new java.lang.Integer (0));
    _methods.put ("modifyPlayer", new java.lang.Integer (1));
    _methods.put ("deletePlayer", new java.lang.Integer (2));
    _methods.put ("searchPlayer", new java.lang.Integer (3));
    _methods.put ("modifyWaitingTime", new java.lang.Integer (4));
    _methods.put ("modifyRoundDuration", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Create a new player account
       case 0:  // IDL_Files.AdminIDL/AdminService/createPlayer
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           String sessionToken = in.read_string ();
           int adminID = in.read_long ();
           this.createPlayer (username, password, sessionToken, adminID);
           out = $rh.createReply();
         } catch (IDL_Files.AdminIDL.AccountExistsException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.AccountExistsExceptionHelper.write (out, $ex);
         } catch (IDL_Files.AdminIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Modify existing player's password
       case 1:  // IDL_Files.AdminIDL/AdminService/modifyPlayer
       {
         try {
           int playerID = in.read_long ();
           String newPassword = in.read_string ();
           String sessionToken = in.read_string ();
           int adminID = in.read_long ();
           this.modifyPlayer (playerID, newPassword, sessionToken, adminID);
           out = $rh.createReply();
         } catch (IDL_Files.AdminIDL.AccountNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.AccountNotFoundExceptionHelper.write (out, $ex);
         } catch (IDL_Files.AdminIDL.ExistingPasswordException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.ExistingPasswordExceptionHelper.write (out, $ex);
         } catch (IDL_Files.AdminIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Delete player account
       case 2:  // IDL_Files.AdminIDL/AdminService/deletePlayer
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           int adminID = in.read_long ();
           this.deletePlayer (playerID, sessionToken, adminID);
           out = $rh.createReply();
         } catch (IDL_Files.AdminIDL.AccountNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.AccountNotFoundExceptionHelper.write (out, $ex);
         } catch (IDL_Files.AdminIDL.AccountCurrentlyActiveException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.AccountCurrentlyActiveExceptionHelper.write (out, $ex);
         } catch (IDL_Files.AdminIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Search for a player by username
       case 3:  // IDL_Files.AdminIDL/AdminService/searchPlayer
       {
         try {
           String username = in.read_string ();
           String sessionToken = in.read_string ();
           int adminID = in.read_long ();
           String $result = null;
           $result = this.searchPlayer (username, sessionToken, adminID);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (IDL_Files.AdminIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.NotLoggedInExceptionHelper.write (out, $ex);
         } catch (IDL_Files.AdminIDL.PlayerNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.PlayerNotFoundExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Change waiting time before game starts
       case 4:  // IDL_Files.AdminIDL/AdminService/modifyWaitingTime
       {
         try {
           int waitTime = in.read_long ();
           String sessionToken = in.read_string ();
           int adminID = in.read_long ();
           this.modifyWaitingTime (waitTime, sessionToken, adminID);
           out = $rh.createReply();
         } catch (IDL_Files.AdminIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Change time duration for each round
       case 5:  // IDL_Files.AdminIDL/AdminService/modifyRoundDuration
       {
         try {
           int roundTime = in.read_long ();
           String sessionToken = in.read_string ();
           int adminID = in.read_long ();
           this.modifyRoundDuration (roundTime, sessionToken, adminID);
           out = $rh.createReply();
         } catch (IDL_Files.AdminIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.AdminIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:IDL_Files.AdminIDL/AdminService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AdminService _this() 
  {
    return AdminServiceHelper.narrow(
    super._this_object());
  }

  public AdminService _this(org.omg.CORBA.ORB orb) 
  {
    return AdminServiceHelper.narrow(
    super._this_object(orb));
  }


} // class AdminServicePOA
