package IDL_Files.AdminIDL;

/**
* IDL_Files.AdminIDL/ExistingPasswordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Saturday, April 26, 2025 2:02:36 PM SGT
*/

public final class ExistingPasswordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public IDL_Files.AdminIDL.ExistingPasswordException value = null;

  public ExistingPasswordExceptionHolder ()
  {
  }

  public ExistingPasswordExceptionHolder (IDL_Files.AdminIDL.ExistingPasswordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL_Files.AdminIDL.ExistingPasswordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL_Files.AdminIDL.ExistingPasswordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL_Files.AdminIDL.ExistingPasswordExceptionHelper.type ();
  }

}
