package IDL_Files.AuthenticationIDL;

/**
* IDL_Files.AuthenticationIDL/AuthenticationExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Saturday, April 26, 2025 2:08:46 PM SGT
*/

public final class AuthenticationExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public IDL_Files.AuthenticationIDL.AuthenticationException value = null;

  public AuthenticationExceptionHolder ()
  {
  }

  public AuthenticationExceptionHolder (IDL_Files.AuthenticationIDL.AuthenticationException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL_Files.AuthenticationIDL.AuthenticationExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL_Files.AuthenticationIDL.AuthenticationExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL_Files.AuthenticationIDL.AuthenticationExceptionHelper.type ();
  }

}
