package IDL_Files.AuthenticationIDL;


/**
* IDL_Files.AuthenticationIDL/AuthenticationServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Saturday, April 26, 2025 2:08:46 PM SGT
*/

abstract public class AuthenticationServiceHelper
{
  private static String  _id = "IDL:IDL_Files.AuthenticationIDL/AuthenticationService:1.0";

  public static void insert (org.omg.CORBA.Any a, IDL_Files.AuthenticationIDL.AuthenticationService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static IDL_Files.AuthenticationIDL.AuthenticationService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (IDL_Files.AuthenticationIDL.AuthenticationServiceHelper.id (), "AuthenticationService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static IDL_Files.AuthenticationIDL.AuthenticationService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AuthenticationServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, IDL_Files.AuthenticationIDL.AuthenticationService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static IDL_Files.AuthenticationIDL.AuthenticationService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof IDL_Files.AuthenticationIDL.AuthenticationService)
      return (IDL_Files.AuthenticationIDL.AuthenticationService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      IDL_Files.AuthenticationIDL._AuthenticationServiceStub stub = new IDL_Files.AuthenticationIDL._AuthenticationServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static IDL_Files.AuthenticationIDL.AuthenticationService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof IDL_Files.AuthenticationIDL.AuthenticationService)
      return (IDL_Files.AuthenticationIDL.AuthenticationService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      IDL_Files.AuthenticationIDL._AuthenticationServiceStub stub = new IDL_Files.AuthenticationIDL._AuthenticationServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
