package IDL_Files.AuthenticationIDL;


/**
* IDL_Files.AuthenticationIDL/AuthenticationService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Saturday, April 26, 2025 2:08:46 PM SGT
*/

public interface AuthenticationService extends AuthenticationServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuthenticationService
