package IDL_Files.AuthenticationIDL;


/**
* IDL_Files.AuthenticationIDL/AuthenticationServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Saturday, April 26, 2025 2:08:46 PM SGT
*/

public interface AuthenticationServiceOperations 
{

  // Player login, returns a session token and player ID
  String login (String username, String password, org.omg.CORBA.IntHolder playerID) throws IDL_Files.AuthenticationIDL.AuthenticationException, IDL_Files.AuthenticationIDL.AlreadyLoggedInException;

  // Player logout using session token
  void logout (int playerID, String sessionToken) throws IDL_Files.AuthenticationIDL.NotLoggedInException;

  // Admin login, returns session token and admin ID
  String adminLogin (String username, String password, org.omg.CORBA.IntHolder adminID) throws IDL_Files.AuthenticationIDL.AuthenticationException, IDL_Files.AuthenticationIDL.AlreadyLoggedInException;

  // Admin logout using session token
  void adminLogout (int adminID, String sessionToken) throws IDL_Files.AuthenticationIDL.NotLoggedInException;
} // interface AuthenticationServiceOperations
