package Admin;


/**
* Admin/AccountExistsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public final class AccountExistsException extends org.omg.CORBA.UserException
{

  public AccountExistsException ()
  {
    super(AccountExistsExceptionHelper.id());
  } // ctor


  public AccountExistsException (String $reason)
  {
    super(AccountExistsExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccountExistsException
