package Admin;

/**
* Admin/AccountNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public final class AccountNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Admin.AccountNotFoundException value = null;

  public AccountNotFoundExceptionHolder ()
  {
  }

  public AccountNotFoundExceptionHolder (Admin.AccountNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Admin.AccountNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Admin.AccountNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Admin.AccountNotFoundExceptionHelper.type ();
  }

}
