package Admin;


/**
* Admin/AccountNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public final class AccountNotFoundException extends org.omg.CORBA.UserException
{

  public AccountNotFoundException ()
  {
    super(AccountNotFoundExceptionHelper.id());
  } // ctor


  public AccountNotFoundException (String $reason)
  {
    super(AccountNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccountNotFoundException
