package Admin;


/**
* Admin/adminServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public abstract class adminServicePOA extends org.omg.PortableServer.Servant
 implements Admin.adminServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createPlayer", new java.lang.Integer (0));
    _methods.put ("modifyPlayer", new java.lang.Integer (1));
    _methods.put ("deletePlayer", new java.lang.Integer (2));
    _methods.put ("searchPlayer", new java.lang.Integer (3));
    _methods.put ("modifyWaitingTime", new java.lang.Integer (4));
    _methods.put ("modifyRoundDuration", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Admin/adminService/createPlayer
       {
         try {
           Admin.Player newPlayer = Admin.PlayerHelper.read (in);
           String sessionToken = in.read_string ();
           int adminID = in.read_long ();
           this.createPlayer (newPlayer, sessionToken, adminID);
           out = $rh.createReply();
         } catch (Admin.AccountExistsException $ex) {
           out = $rh.createExceptionReply ();
           Admin.AccountExistsExceptionHelper.write (out, $ex);
         } catch (Admin.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Admin.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // Admin/adminService/modifyPlayer
       {
         try {
           int playerID = in.read_long ();
           String newPassword = in.read_string ();
           String sessionToken = in.read_string ();
           int adminID = in.read_long ();
           this.modifyPlayer (playerID, newPassword, sessionToken, adminID);
           out = $rh.createReply();
         } catch (Admin.AccountNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           Admin.AccountNotFoundExceptionHelper.write (out, $ex);
         } catch (Admin.ExistingPasswordException $ex) {
           out = $rh.createExceptionReply ();
           Admin.ExistingPasswordExceptionHelper.write (out, $ex);
         } catch (Admin.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Admin.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // Admin/adminService/deletePlayer
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           int adminID = in.read_long ();
           this.deletePlayer (playerID, sessionToken, adminID);
           out = $rh.createReply();
         } catch (Admin.AccountNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           Admin.AccountNotFoundExceptionHelper.write (out, $ex);
         } catch (Admin.AccountCurrentlyActiveException $ex) {
           out = $rh.createExceptionReply ();
           Admin.AccountCurrentlyActiveExceptionHelper.write (out, $ex);
         } catch (Admin.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Admin.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // Admin/adminService/searchPlayer
       {
         try {
           int playerID = in.read_long ();
           String username = in.read_string ();
           String sessionToken = in.read_string ();
           Admin.Player $result = null;
           $result = this.searchPlayer (playerID, username, sessionToken);
           out = $rh.createReply();
           Admin.PlayerHelper.write (out, $result);
         } catch (Admin.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Admin.NotLoggedInExceptionHelper.write (out, $ex);
         } catch (Admin.PlayerNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           Admin.PlayerNotFoundExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // Admin/adminService/modifyWaitingTime
       {
         try {
           int waitTime = in.read_long ();
           String sessionToken = in.read_string ();
           int adminID = in.read_long ();
           this.modifyWaitingTime (waitTime, sessionToken, adminID);
           out = $rh.createReply();
         } catch (Admin.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Admin.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // Admin/adminService/modifyRoundDuration
       {
         try {
           int roundTime = in.read_long ();
           String sessionToken = in.read_string ();
           int adminID = in.read_long ();
           this.modifyRoundDuration (roundTime, sessionToken, adminID);
           out = $rh.createReply();
         } catch (Admin.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Admin.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Admin/adminService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public adminService _this() 
  {
    return adminServiceHelper.narrow(
    super._this_object());
  }

  public adminService _this(org.omg.CORBA.ORB orb) 
  {
    return adminServiceHelper.narrow(
    super._this_object(orb));
  }


} // class adminServicePOA
