package Admin;


/**
* Admin/adminAuthServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public abstract class adminAuthServicePOA extends org.omg.PortableServer.Servant
 implements Admin.adminAuthServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("adminLogin", new java.lang.Integer (0));
    _methods.put ("adminLogout", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Admin/adminAuthService/adminLogin
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           org.omg.CORBA.IntHolder adminID = new org.omg.CORBA.IntHolder ();
           String $result = null;
           $result = this.adminLogin (username, password, adminID);
           out = $rh.createReply();
           out.write_string ($result);
           out.write_long (adminID.value);
         } catch (Admin.AuthenticationException $ex) {
           out = $rh.createExceptionReply ();
           Admin.AuthenticationExceptionHelper.write (out, $ex);
         } catch (Admin.AlreadyLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Admin.AlreadyLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // Admin/adminAuthService/adminLogout
       {
         try {
           int adminID = in.read_long ();
           String sessionToken = in.read_string ();
           this.adminLogout (adminID, sessionToken);
           out = $rh.createReply();
         } catch (Admin.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Admin.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Admin/adminAuthService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public adminAuthService _this() 
  {
    return adminAuthServiceHelper.narrow(
    super._this_object());
  }

  public adminAuthService _this(org.omg.CORBA.ORB orb) 
  {
    return adminAuthServiceHelper.narrow(
    super._this_object(orb));
  }


} // class adminAuthServicePOA
