package Admin;


/**
* Admin/adminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public interface adminServiceOperations 
{
  void createPlayer (Admin.Player newPlayer, String sessionToken, int adminID) throws Admin.AccountExistsException, Admin.NotLoggedInException;
  void modifyPlayer (int playerID, String newPassword, String sessionToken, int adminID) throws Admin.AccountNotFoundException, Admin.ExistingPasswordException, Admin.NotLoggedInException;
  void deletePlayer (int playerID, String sessionToken, int adminID) throws Admin.AccountNotFoundException, Admin.AccountCurrentlyActiveException, Admin.NotLoggedInException;
  Admin.Player searchPlayer (int playerID, String username, String sessionToken) throws Admin.NotLoggedInException, Admin.PlayerNotFoundException;
  void modifyWaitingTime (int waitTime, String sessionToken, int adminID) throws Admin.NotLoggedInException;
  void modifyRoundDuration (int roundTime, String sessionToken, int adminID) throws Admin.NotLoggedInException;
} // interface adminServiceOperations
