package Admin;


/**
* Admin/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public final class Admin implements org.omg.CORBA.portable.IDLEntity
{
  public int adminID = (int)0;
  public String fullName = null;
  public String username = null;

  public Admin ()
  {
  } // ctor

  public Admin (int _adminID, String _fullName, String _username)
  {
    adminID = _adminID;
    fullName = _fullName;
    username = _username;
  } // ctor

} // class Admin
