package Admin;


/**
* Admin/adminServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

abstract public class adminServiceHelper
{
  private static String  _id = "IDL:Admin/adminService:1.0";

  public static void insert (org.omg.CORBA.Any a, Admin.adminService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Admin.adminService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Admin.adminServiceHelper.id (), "adminService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Admin.adminService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_adminServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Admin.adminService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Admin.adminService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Admin.adminService)
      return (Admin.adminService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Admin._adminServiceStub stub = new Admin._adminServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Admin.adminService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Admin.adminService)
      return (Admin.adminService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Admin._adminServiceStub stub = new Admin._adminServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
