package Admin;


/**
* Admin/adminAuthService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public interface adminAuthService extends adminAuthServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface adminAuthService
