package Admin;


/**
* Admin/AuthenticationException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public final class AuthenticationException extends org.omg.CORBA.UserException
{

  public AuthenticationException ()
  {
    super(AuthenticationExceptionHelper.id());
  } // ctor


  public AuthenticationException (String $reason)
  {
    super(AuthenticationExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AuthenticationException
