package Admin;

/**
* Admin/AuthenticationExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public final class AuthenticationExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Admin.AuthenticationException value = null;

  public AuthenticationExceptionHolder ()
  {
  }

  public AuthenticationExceptionHolder (Admin.AuthenticationException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Admin.AuthenticationExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Admin.AuthenticationExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Admin.AuthenticationExceptionHelper.type ();
  }

}
