package Admin;

/**
* Admin/ExistingPasswordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public final class ExistingPasswordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Admin.ExistingPasswordException value = null;

  public ExistingPasswordExceptionHolder ()
  {
  }

  public ExistingPasswordExceptionHolder (Admin.ExistingPasswordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Admin.ExistingPasswordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Admin.ExistingPasswordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Admin.ExistingPasswordExceptionHelper.type ();
  }

}
