package Admin;


/**
* Admin/ExistingPasswordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public final class ExistingPasswordException extends org.omg.CORBA.UserException
{

  public ExistingPasswordException ()
  {
    super(ExistingPasswordExceptionHelper.id());
  } // ctor


  public ExistingPasswordException (String $reason)
  {
    super(ExistingPasswordExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class ExistingPasswordException
