package Admin;


/**
* Admin/NotLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, April 22, 2025 11:18:36 PM CST
*/

public final class NotLoggedInException extends org.omg.CORBA.UserException
{

  public NotLoggedInException ()
  {
    super(NotLoggedInExceptionHelper.id());
  } // ctor


  public NotLoggedInException (String $reason)
  {
    super(NotLoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NotLoggedInException
