package IDL_Files.PlayerCallBackIDL;


/**
* IDL_Files.PlayerCallBackIDL/_PlayerCallBackServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Saturday, April 26, 2025 2:03:17 PM SGT
*/

public class _PlayerCallBackServiceStub extends org.omg.CORBA.portable.ObjectImpl implements IDL_Files.PlayerCallBackIDL.PlayerCallBackService
{


  // Notify player about end of round
  public void notifyRoundEnd (String gameToken, String sessionToken, String result)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("notifyRoundEnd", true);
                $out.write_string (gameToken);
                $out.write_string (sessionToken);
                $out.write_string (result);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                notifyRoundEnd (gameToken, sessionToken, result        );
            } finally {
                _releaseReply ($in);
            }
  } // notifyRoundEnd


  // Notify player about end of game
  public void notifyGameEnd (String gameToken, String sessionToken, String result)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("notifyGameEnd", true);
                $out.write_string (gameToken);
                $out.write_string (sessionToken);
                $out.write_string (result);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                notifyGameEnd (gameToken, sessionToken, result        );
            } finally {
                _releaseReply ($in);
            }
  } // notifyGameEnd


  // Forcefully logout player (used by admin)
  public void notifyForcedLogout (int playerID, String sessionToken) throws IDL_Files.PlayerCallBackIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("notifyForcedLogout", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.PlayerCallBackIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.PlayerCallBackIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                notifyForcedLogout (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // notifyForcedLogout

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:IDL_Files.PlayerCallBackIDL/PlayerCallBackService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "IDL_Files.PlayerCallBackIDL._PlayerCallBackServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PlayerCallBackServiceStub
