package IDL_Files.PlayerCallBackIDL;

/**
* IDL_Files.PlayerCallBackIDL/PlayerCallBackServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Saturday, April 26, 2025 2:03:17 PM SGT
*/

public final class PlayerCallBackServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public IDL_Files.PlayerCallBackIDL.PlayerCallBackService value = null;

  public PlayerCallBackServiceHolder ()
  {
  }

  public PlayerCallBackServiceHolder (IDL_Files.PlayerCallBackIDL.PlayerCallBackService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL_Files.PlayerCallBackIDL.PlayerCallBackServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL_Files.PlayerCallBackIDL.PlayerCallBackServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL_Files.PlayerCallBackIDL.PlayerCallBackServiceHelper.type ();
  }

}
