package IDL_Files.PlayerCallBackIDL;


/**
* IDL_Files.PlayerCallBackIDL/PlayerCallBackServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Saturday, April 26, 2025 2:03:17 PM SGT
*/

public interface PlayerCallBackServiceOperations 
{

  // Notify player about end of round
  void notifyRoundEnd (String gameToken, String sessionToken, String result);

  // Notify player about end of game
  void notifyGameEnd (String gameToken, String sessionToken, String result);

  // Forcefully logout player (used by admin)
  void notifyForcedLogout (int playerID, String sessionToken) throws IDL_Files.PlayerCallBackIDL.NotLoggedInException;
} // interface PlayerCallBackServiceOperations
