package IDL_Files.PlayerCallBackIDL;


/**
* IDL_Files.PlayerCallBackIDL/PlayerCallBackService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Saturday, April 26, 2025 2:03:17 PM SGT
*/

public interface PlayerCallBackService extends PlayerCallBackServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerCallBackService
