package IDL_Files.PlayerCallBackIDL;


/**
* IDL_Files.PlayerCallBackIDL/PlayerCallBackServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Saturday, April 26, 2025 2:03:17 PM SGT
*/

public abstract class PlayerCallBackServicePOA extends org.omg.PortableServer.Servant
 implements IDL_Files.PlayerCallBackIDL.PlayerCallBackServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notifyRoundEnd", new java.lang.Integer (0));
    _methods.put ("notifyGameEnd", new java.lang.Integer (1));
    _methods.put ("notifyForcedLogout", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Notify player about end of round
       case 0:  // IDL_Files.PlayerCallBackIDL/PlayerCallBackService/notifyRoundEnd
       {
         String gameToken = in.read_string ();
         String sessionToken = in.read_string ();
         String result = in.read_string ();
         this.notifyRoundEnd (gameToken, sessionToken, result);
         out = $rh.createReply();
         break;
       }


  // Notify player about end of game
       case 1:  // IDL_Files.PlayerCallBackIDL/PlayerCallBackService/notifyGameEnd
       {
         String gameToken = in.read_string ();
         String sessionToken = in.read_string ();
         String result = in.read_string ();
         this.notifyGameEnd (gameToken, sessionToken, result);
         out = $rh.createReply();
         break;
       }


  // Forcefully logout player (used by admin)
       case 2:  // IDL_Files.PlayerCallBackIDL/PlayerCallBackService/notifyForcedLogout
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           this.notifyForcedLogout (playerID, sessionToken);
           out = $rh.createReply();
         } catch (IDL_Files.PlayerCallBackIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           IDL_Files.PlayerCallBackIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:IDL_Files.PlayerCallBackIDL/PlayerCallBackService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PlayerCallBackService _this() 
  {
    return PlayerCallBackServiceHelper.narrow(
    super._this_object());
  }

  public PlayerCallBackService _this(org.omg.CORBA.ORB orb) 
  {
    return PlayerCallBackServiceHelper.narrow(
    super._this_object(orb));
  }


} // class PlayerCallBackServicePOA
