package IDL_Files.GameIDL;


/**
* IDL_Files.GameIDL/_GameServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Saturday, April 26, 2025 2:14:10 PM SGT
*/

public class _GameServiceStub extends org.omg.CORBA.portable.ObjectImpl implements IDL_Files.GameIDL.GameService
{


  // Get display name of a player
  public String getDisplayName (String username, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getDisplayName", true);
                $out.write_string (username);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getDisplayName (username, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getDisplayName


  // Get top players in leaderboard
  public String[] getLeaderboards (int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLeaderboards", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result[] = IDL_Files.GameIDL.StringListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLeaderboards (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getLeaderboards


  // Join game waiting lobby
  public String joinWaitingLobby (int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("joinWaitingLobby", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return joinWaitingLobby (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // joinWaitingLobby


  // Register callback object for game events
  public void registerCallBack (int playerID, String gameToken, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerCallBack", true);
                $out.write_long (playerID);
                $out.write_string (gameToken);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerCallBack (playerID, gameToken, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // registerCallBack


  // Check lobby status (used for countdown/waiting info)
  public String getWaitingLobbyStatus (String gameToken) throws IDL_Files.GameIDL.NotLoggedInException, IDL_Files.GameIDL.GameTimeOutException, IDL_Files.GameIDL.NotEnoughPlayersException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getWaitingLobbyStatus", true);
                $out.write_string (gameToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else if (_id.equals ("IDL:IDL_Files.GameIDL/GameTimeOutException:1.0"))
                    throw IDL_Files.GameIDL.GameTimeOutExceptionHelper.read ($in);
                else if (_id.equals ("IDL:IDL_Files.GameIDL/NotEnoughPlayersException:1.0"))
                    throw IDL_Files.GameIDL.NotEnoughPlayersExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getWaitingLobbyStatus (gameToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getWaitingLobbyStatus


  // Get number of players in the lobby
  public int getNumberOfPlayersJoined (int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNumberOfPlayersJoined", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getNumberOfPlayersJoined (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getNumberOfPlayersJoined


  // Initiate game when enough players have joined
  public int startGame (int playerID, String sessionToken) throws IDL_Files.GameIDL.NotEnoughPlayersException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startGame", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/NotEnoughPlayersException:1.0"))
                    throw IDL_Files.GameIDL.NotEnoughPlayersExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startGame (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // startGame


  // Start a new game round
  public int startRound (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.GameNotFoundException, IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startRound", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/GameNotFoundException:1.0"))
                    throw IDL_Files.GameIDL.GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startRound (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // startRound


  // Get random word to guess (only at round start)
  public String getRandomWord (String gameToken, int roundNumber, int playerID, String sessionToken) throws IDL_Files.GameIDL.GameNotFoundException, IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRandomWord", true);
                $out.write_string (gameToken);
                $out.write_long (roundNumber);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/GameNotFoundException:1.0"))
                    throw IDL_Files.GameIDL.GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRandomWord (gameToken, roundNumber, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRandomWord


  // Submit a letter guess
  public int[] guessLetter (String gameToken, int playerID, String sessionToken, char letter) throws IDL_Files.GameIDL.MaxAttemptsReachedException, IDL_Files.GameIDL.GameNotFoundException, IDL_Files.GameIDL.AlreadyGuessedLetterException, IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("guessLetter", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $out.write_char (letter);
                $in = _invoke ($out);
                int $result[] = IDL_Files.GameIDL.IndexListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/MaxAttemptsReachedException:1.0"))
                    throw IDL_Files.GameIDL.MaxAttemptsReachedExceptionHelper.read ($in);
                else if (_id.equals ("IDL:IDL_Files.GameIDL/GameNotFoundException:1.0"))
                    throw IDL_Files.GameIDL.GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:IDL_Files.GameIDL/AlreadyGuessedLetterException:1.0"))
                    throw IDL_Files.GameIDL.AlreadyGuessedLetterExceptionHelper.read ($in);
                else if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return guessLetter (gameToken, playerID, sessionToken, letter        );
            } finally {
                _releaseReply ($in);
            }
  } // guessLetter


  // Get remaining wait time before game starts
  public int getRemainingWaitingTime (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.GameTimeOutException, IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRemainingWaitingTime", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/GameTimeOutException:1.0"))
                    throw IDL_Files.GameIDL.GameTimeOutExceptionHelper.read ($in);
                else if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRemainingWaitingTime (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRemainingWaitingTime


  // Get remaining time for the current round
  public int getRemainingRoundTime (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.GameTimeOutException, IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRemainingRoundTime", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/GameTimeOutException:1.0"))
                    throw IDL_Files.GameIDL.GameTimeOutExceptionHelper.read ($in);
                else if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRemainingRoundTime (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRemainingRoundTime


  // Get winner of the current round
  public String getRoundWinner (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRoundWinner", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRoundWinner (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRoundWinner


  // Get winner of the game
  public String getGameWinner (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getGameWinner", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getGameWinner (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getGameWinner


  // Get number of wins for a player in current game
  public int getPlayerWins (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPlayerWins", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:IDL_Files.GameIDL/NotLoggedInException:1.0"))
                    throw IDL_Files.GameIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPlayerWins (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getPlayerWins

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:IDL_Files.GameIDL/GameService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "IDL_Files.GameIDL._GameServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GameServiceStub
