package IDL_Files.GameIDL;


/**
* IDL_Files.GameIDL/AlreadyGuessedLetterException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Saturday, April 26, 2025 2:14:10 PM SGT
*/

public final class AlreadyGuessedLetterException extends org.omg.CORBA.UserException
{

  public AlreadyGuessedLetterException ()
  {
    super(AlreadyGuessedLetterExceptionHelper.id());
  } // ctor


  public AlreadyGuessedLetterException (String $reason)
  {
    super(AlreadyGuessedLetterExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyGuessedLetterException
