package IDL_Files.GameIDL;

/**
* IDL_Files.GameIDL/AlreadyGuessedLetterExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Saturday, April 26, 2025 2:14:10 PM SGT
*/

public final class AlreadyGuessedLetterExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public IDL_Files.GameIDL.AlreadyGuessedLetterException value = null;

  public AlreadyGuessedLetterExceptionHolder ()
  {
  }

  public AlreadyGuessedLetterExceptionHolder (IDL_Files.GameIDL.AlreadyGuessedLetterException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL_Files.GameIDL.AlreadyGuessedLetterExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL_Files.GameIDL.AlreadyGuessedLetterExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL_Files.GameIDL.AlreadyGuessedLetterExceptionHelper.type ();
  }

}
