package IDL_Files.GameIDL;

/**
* IDL_Files.GameIDL/GameNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Saturday, April 26, 2025 2:14:09 PM SGT
*/

public final class GameNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public IDL_Files.GameIDL.GameNotFoundException value = null;

  public GameNotFoundExceptionHolder ()
  {
  }

  public GameNotFoundExceptionHolder (IDL_Files.GameIDL.GameNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL_Files.GameIDL.GameNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL_Files.GameIDL.GameNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL_Files.GameIDL.GameNotFoundExceptionHelper.type ();
  }

}
