package IDL_Files.GameIDL;


/**
* IDL_Files.GameIDL/GameTimeOutException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Saturday, April 26, 2025 2:14:09 PM SGT
*/

public final class GameTimeOutException extends org.omg.CORBA.UserException
{

  public GameTimeOutException ()
  {
    super(GameTimeOutExceptionHelper.id());
  } // ctor


  public GameTimeOutException (String $reason)
  {
    super(GameTimeOutExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class GameTimeOutException
