package IDL_Files.GameIDL;


/**
* IDL_Files.GameIDL/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Saturday, April 26, 2025 2:14:10 PM SGT
*/

public interface GameServiceOperations 
{

  // Get display name of a player
  String getDisplayName (String username, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException;

  // Get top players in leaderboard
  String[] getLeaderboards (int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException;

  // Join game waiting lobby
  String joinWaitingLobby (int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException;

  // Register callback object for game events
  void registerCallBack (int playerID, String gameToken, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException;

  // Check lobby status (used for countdown/waiting info)
  String getWaitingLobbyStatus (String gameToken) throws IDL_Files.GameIDL.NotLoggedInException, IDL_Files.GameIDL.GameTimeOutException, IDL_Files.GameIDL.NotEnoughPlayersException;

  // Get number of players in the lobby
  int getNumberOfPlayersJoined (int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException;

  // Initiate game when enough players have joined
  int startGame (int playerID, String sessionToken) throws IDL_Files.GameIDL.NotEnoughPlayersException;

  // Start a new game round
  int startRound (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.GameNotFoundException, IDL_Files.GameIDL.NotLoggedInException;

  // Get random word to guess (only at round start)
  String getRandomWord (String gameToken, int roundNumber, int playerID, String sessionToken) throws IDL_Files.GameIDL.GameNotFoundException, IDL_Files.GameIDL.NotLoggedInException;

  // Submit a letter guess
  int[] guessLetter (String gameToken, int playerID, String sessionToken, char letter) throws IDL_Files.GameIDL.MaxAttemptsReachedException, IDL_Files.GameIDL.GameNotFoundException, IDL_Files.GameIDL.AlreadyGuessedLetterException, IDL_Files.GameIDL.NotLoggedInException;

  // Get remaining wait time before game starts
  int getRemainingWaitingTime (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.GameTimeOutException, IDL_Files.GameIDL.NotLoggedInException;

  // Get remaining time for the current round
  int getRemainingRoundTime (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.GameTimeOutException, IDL_Files.GameIDL.NotLoggedInException;

  // Get winner of the current round
  String getRoundWinner (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException;

  // Get winner of the game
  String getGameWinner (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException;

  // Get number of wins for a player in current game
  int getPlayerWins (String gameToken, int playerID, String sessionToken) throws IDL_Files.GameIDL.NotLoggedInException;
} // interface GameServiceOperations
