package IDL_Files.GameIDL;


/**
* IDL_Files.GameIDL/IndexListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Saturday, April 26, 2025 2:14:09 PM SGT
*/

public final class IndexListHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public IndexListHolder ()
  {
  }

  public IndexListHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL_Files.GameIDL.IndexListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL_Files.GameIDL.IndexListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL_Files.GameIDL.IndexListHelper.type ();
  }

}
