package IDL_Files.GameIDL;

/**
* IDL_Files.GameIDL/MaxAttemptsReachedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Saturday, April 26, 2025 2:14:10 PM SGT
*/

public final class MaxAttemptsReachedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public IDL_Files.GameIDL.MaxAttemptsReachedException value = null;

  public MaxAttemptsReachedExceptionHolder ()
  {
  }

  public MaxAttemptsReachedExceptionHolder (IDL_Files.GameIDL.MaxAttemptsReachedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL_Files.GameIDL.MaxAttemptsReachedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL_Files.GameIDL.MaxAttemptsReachedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL_Files.GameIDL.MaxAttemptsReachedExceptionHelper.type ();
  }

}
