package IDL_Files.GameIDL;


/**
* IDL_Files.GameIDL/NotEnoughPlayersException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Saturday, April 26, 2025 2:14:09 PM SGT
*/

public final class NotEnoughPlayersException extends org.omg.CORBA.UserException
{

  public NotEnoughPlayersException ()
  {
    super(NotEnoughPlayersExceptionHelper.id());
  } // ctor


  public NotEnoughPlayersException (String $reason)
  {
    super(NotEnoughPlayersExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NotEnoughPlayersException
