package Server_Java.idls.PlayerCallBackIDL;


/**
* PlayerCallBackIDL/GameCallBackServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerCallBack.idl
* Tuesday, April 29, 2025 5:49:28 PM CST
*/


// Callbacks for game events
public interface GameCallBackServiceOperations 
{
  void notifyGameStart (String gameToken, String sessionToken);
  void notifyRoundStart (String gameToken, int roundNumber, String sessionToken);
  void notifyRoundEnd (String gameToken, String sessionToken, String result);
  void notifyGameEnd (String gameToken, String sessionToken, String result);
} // interface GameCallBackServiceOperations
