package Server_Java.idls.PlayerCallBackIDL;


/**
* Server_Java.idls.PlayerCallBackIDL/GameCallBackServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerCallBack.idl
* Wednesday, April 30, 2025 12:17:57 AM CST
*/


// Callbacks for game events
abstract public class GameCallBackServiceHelper
{
  private static String  _id = "IDL:Server_Java.idls.PlayerCallBackIDL/GameCallBackService:1.0";

  public static void insert (org.omg.CORBA.Any a, Server_Java.idls.PlayerCallBackIDL.GameCallBackService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Server_Java.idls.PlayerCallBackIDL.GameCallBackService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Server_Java.idls.PlayerCallBackIDL.GameCallBackServiceHelper.id (), "GameCallBackService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Server_Java.idls.PlayerCallBackIDL.GameCallBackService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameCallBackServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Server_Java.idls.PlayerCallBackIDL.GameCallBackService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Server_Java.idls.PlayerCallBackIDL.GameCallBackService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Server_Java.idls.PlayerCallBackIDL.GameCallBackService)
      return (Server_Java.idls.PlayerCallBackIDL.GameCallBackService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Server_Java.idls.PlayerCallBackIDL._GameCallBackServiceStub stub = new Server_Java.idls.PlayerCallBackIDL._GameCallBackServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Server_Java.idls.PlayerCallBackIDL.GameCallBackService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Server_Java.idls.PlayerCallBackIDL.GameCallBackService)
      return (Server_Java.idls.PlayerCallBackIDL.GameCallBackService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Server_Java.idls.PlayerCallBackIDL._GameCallBackServiceStub stub = new Server_Java.idls.PlayerCallBackIDL._GameCallBackServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
