package Server_Java.idls.PlayerCallBackIDL;

/**
* Server_Java.idls.PlayerCallBackIDL/GameCallBackServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerCallBack.idl
* Wednesday, April 30, 2025 12:17:57 AM CST
*/


// Callbacks for game events
public final class GameCallBackServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Java.idls.PlayerCallBackIDL.GameCallBackService value = null;

  public GameCallBackServiceHolder ()
  {
  }

  public GameCallBackServiceHolder (Server_Java.idls.PlayerCallBackIDL.GameCallBackService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Java.idls.PlayerCallBackIDL.GameCallBackServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Java.idls.PlayerCallBackIDL.GameCallBackServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Java.idls.PlayerCallBackIDL.GameCallBackServiceHelper.type ();
  }

}
