package Server_Java.idls.PlayerCallBackIDL;


/**
* Server_Java.idls.PlayerCallBackIDL/GameCallBackServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerCallBack.idl
* Wednesday, April 30, 2025 12:17:57 AM CST
*/


// Callbacks for game events
public abstract class GameCallBackServicePOA extends org.omg.PortableServer.Servant
 implements Server_Java.idls.PlayerCallBackIDL.GameCallBackServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notifyGameStart", new java.lang.Integer (0));
    _methods.put ("notifyRoundStart", new java.lang.Integer (1));
    _methods.put ("notifyRoundEnd", new java.lang.Integer (2));
    _methods.put ("notifyGameEnd", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Server_Java.idls.PlayerCallBackIDL/GameCallBackService/notifyGameStart
       {
         String gameToken = in.read_string ();
         String sessionToken = in.read_string ();
         this.notifyGameStart (gameToken, sessionToken);
         out = $rh.createReply();
         break;
       }

       case 1:  // Server_Java.idls.PlayerCallBackIDL/GameCallBackService/notifyRoundStart
       {
         String gameToken = in.read_string ();
         int roundNumber = in.read_long ();
         String sessionToken = in.read_string ();
         this.notifyRoundStart (gameToken, roundNumber, sessionToken);
         out = $rh.createReply();
         break;
       }

       case 2:  // Server_Java.idls.PlayerCallBackIDL/GameCallBackService/notifyRoundEnd
       {
         String gameToken = in.read_string ();
         String sessionToken = in.read_string ();
         String result = in.read_string ();
         this.notifyRoundEnd (gameToken, sessionToken, result);
         out = $rh.createReply();
         break;
       }

       case 3:  // Server_Java.idls.PlayerCallBackIDL/GameCallBackService/notifyGameEnd
       {
         String gameToken = in.read_string ();
         String sessionToken = in.read_string ();
         String result = in.read_string ();
         this.notifyGameEnd (gameToken, sessionToken, result);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Server_Java.idls.PlayerCallBackIDL/GameCallBackService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameCallBackService _this() 
  {
    return GameCallBackServiceHelper.narrow(
    super._this_object());
  }

  public GameCallBackService _this(org.omg.CORBA.ORB orb) 
  {
    return GameCallBackServiceHelper.narrow(
    super._this_object(orb));
  }


} // class GameCallBackServicePOA
