package Server_Java.idls.PlayerCallBackIDL;


/**
* Server_Java.idls.PlayerCallBackIDL/LoginCallbackService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerCallBack.idl
* Wednesday, April 30, 2025 12:17:57 AM CST
*/


// Callback that the server uses to force��logout a player
public interface LoginCallbackService extends LoginCallbackServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LoginCallbackService
