package Server_Java.idls.PlayerCallBackIDL;

/**
* Server_Java.idls.PlayerCallBackIDL/LoginCallbackServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerCallBack.idl
* Wednesday, April 30, 2025 12:17:57 AM CST
*/


// Callback that the server uses to force��logout a player
public final class LoginCallbackServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Java.idls.PlayerCallBackIDL.LoginCallbackService value = null;

  public LoginCallbackServiceHolder ()
  {
  }

  public LoginCallbackServiceHolder (Server_Java.idls.PlayerCallBackIDL.LoginCallbackService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Java.idls.PlayerCallBackIDL.LoginCallbackServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Java.idls.PlayerCallBackIDL.LoginCallbackServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Java.idls.PlayerCallBackIDL.LoginCallbackServiceHelper.type ();
  }

}
