package Server_Java.idls.PlayerCallBackIDL;

/**
* PlayerCallBackIDL/LoginCallbackServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerCallBack.idl
* Tuesday, April 29, 2025 5:49:28 PM CST
*/


// Callback that the server uses to force��logout a player
public final class LoginCallbackServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public LoginCallbackService value = null;

  public LoginCallbackServiceHolder ()
  {
  }

  public LoginCallbackServiceHolder (LoginCallbackService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LoginCallbackServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LoginCallbackServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LoginCallbackServiceHelper.type ();
  }

}
