package Server_Java.idls.PlayerCallBackIDL;


/**
* Server_Java.idls.PlayerCallBackIDL/WaitingRoomGameCallbackServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerCallBack.idl
* Wednesday, April 30, 2025 12:17:57 AM CST
*/

public abstract class WaitingRoomGameCallbackServicePOA extends org.omg.PortableServer.Servant
 implements Server_Java.idls.PlayerCallBackIDL.WaitingRoomGameCallbackServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notifyPlayerJoined", new java.lang.Integer (0));
    _methods.put ("notifyCountdownStart", new java.lang.Integer (1));
    _methods.put ("notifyCountdownReset", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // A new player has joined the lobby; totalPlayers is the current count
       case 0:  // Server_Java.idls.PlayerCallBackIDL/WaitingRoomGameCallbackService/notifyPlayerJoined
       {
         try {
           String gameToken = in.read_string ();
           int totalPlayers = in.read_long ();
           String sessionToken = in.read_string ();
           this.notifyPlayerJoined (gameToken, totalPlayers, sessionToken);
           out = $rh.createReply();
         } catch (Server_Java.idls.PlayerCallBackIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server_Java.idls.PlayerCallBackIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Time to start the synchronized countdown
       case 1:  // Server_Java.idls.PlayerCallBackIDL/WaitingRoomGameCallbackService/notifyCountdownStart
       {
         try {
           String gameToken = in.read_string ();
           int countdownSeconds = in.read_long ();
           String sessionToken = in.read_string ();
           this.notifyCountdownStart (gameToken, countdownSeconds, sessionToken);
           out = $rh.createReply();
         } catch (Server_Java.idls.PlayerCallBackIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server_Java.idls.PlayerCallBackIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Countdown aborted/reset because someone left
       case 2:  // Server_Java.idls.PlayerCallBackIDL/WaitingRoomGameCallbackService/notifyCountdownReset
       {
         try {
           String gameToken = in.read_string ();
           String sessionToken = in.read_string ();
           this.notifyCountdownReset (gameToken, sessionToken);
           out = $rh.createReply();
         } catch (Server_Java.idls.PlayerCallBackIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server_Java.idls.PlayerCallBackIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Server_Java.idls.PlayerCallBackIDL/WaitingRoomGameCallbackService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public WaitingRoomGameCallbackService _this() 
  {
    return WaitingRoomGameCallbackServiceHelper.narrow(
    super._this_object());
  }

  public WaitingRoomGameCallbackService _this(org.omg.CORBA.ORB orb) 
  {
    return WaitingRoomGameCallbackServiceHelper.narrow(
    super._this_object(orb));
  }


} // class WaitingRoomGameCallbackServicePOA
