package Server_Java.idls.PlayerCallBackIDL;


/**
* Server_Java.idls.PlayerCallBackIDL/WaitingRoomGameCallbackServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerCallBack.idl
* Wednesday, April 30, 2025 12:17:57 AM CST
*/

public interface WaitingRoomGameCallbackServiceOperations 
{

  // A new player has joined the lobby; totalPlayers is the current count
  void notifyPlayerJoined (String gameToken, int totalPlayers, String sessionToken) throws Server_Java.idls.PlayerCallBackIDL.NotLoggedInException;

  // Time to start the synchronized countdown
  void notifyCountdownStart (String gameToken, int countdownSeconds, String sessionToken) throws Server_Java.idls.PlayerCallBackIDL.NotLoggedInException;

  // Countdown aborted/reset because someone left
  void notifyCountdownReset (String gameToken, String sessionToken) throws Server_Java.idls.PlayerCallBackIDL.NotLoggedInException;
} // interface WaitingRoomGameCallbackServiceOperations
