package Server_Java.idls.PlayerCallBackIDL;

/**
* Server_Java.idls.PlayerCallBackIDL/WaitingRoomGameCallbackServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./PlayerCallBack.idl
* Wednesday, April 30, 2025 12:17:57 AM CST
*/

public final class WaitingRoomGameCallbackServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Java.idls.PlayerCallBackIDL.WaitingRoomGameCallbackService value = null;

  public WaitingRoomGameCallbackServiceHolder ()
  {
  }

  public WaitingRoomGameCallbackServiceHolder (Server_Java.idls.PlayerCallBackIDL.WaitingRoomGameCallbackService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Java.idls.PlayerCallBackIDL.WaitingRoomGameCallbackServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Java.idls.PlayerCallBackIDL.WaitingRoomGameCallbackServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Java.idls.PlayerCallBackIDL.WaitingRoomGameCallbackServiceHelper.type ();
  }

}
