package PlayerCallBackIDL;


/**
* PlayerCallBackIDL/_GameCallBackServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Wednesday, May 7, 2025 8:53:42 AM CST
*/


// Callbacks for game events
public class _GameCallBackServiceStub extends org.omg.CORBA.portable.ObjectImpl implements PlayerCallBackIDL.GameCallBackService
{

  public void notifyGameStart (String gameToken, String sessionToken)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("notifyGameStart", true);
                $out.write_string (gameToken);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                notifyGameStart (gameToken, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // notifyGameStart

  public void notifyRoundStart (String gameToken, int roundNumber, String sessionToken)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("notifyRoundStart", true);
                $out.write_string (gameToken);
                $out.write_long (roundNumber);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                notifyRoundStart (gameToken, roundNumber, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // notifyRoundStart

  public void notifyRoundEnd (String gameToken, String sessionToken, String result)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("notifyRoundEnd", true);
                $out.write_string (gameToken);
                $out.write_string (sessionToken);
                $out.write_string (result);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                notifyRoundEnd (gameToken, sessionToken, result        );
            } finally {
                _releaseReply ($in);
            }
  } // notifyRoundEnd

  public void notifyGameEnd (String gameToken, String sessionToken, String result)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("notifyGameEnd", true);
                $out.write_string (gameToken);
                $out.write_string (sessionToken);
                $out.write_string (result);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                notifyGameEnd (gameToken, sessionToken, result        );
            } finally {
                _releaseReply ($in);
            }
  } // notifyGameEnd

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PlayerCallBackIDL/GameCallBackService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "PlayerCallBackIDL._GameCallBackServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GameCallBackServiceStub
