package PlayerCallBackIDL;


/**
* PlayerCallBackIDL/GameCallBackServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Wednesday, May 7, 2025 8:53:42 AM CST
*/


// Callbacks for game events
public interface GameCallBackServiceOperations 
{
  void notifyGameStart (String gameToken, String sessionToken);
  void notifyRoundStart (String gameToken, int roundNumber, String sessionToken);
  void notifyRoundEnd (String gameToken, String sessionToken, String result);
  void notifyGameEnd (String gameToken, String sessionToken, String result);
} // interface GameCallBackServiceOperations
