package PlayerCallBackIDL;


/**
* PlayerCallBackIDL/GameCallBackServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Thursday, May 8, 2025 9:36:15 PM SGT
*/


// Callbacks for game events
public interface GameCallBackServiceOperations 
{
  void notifyGameStart (String gameToken, String sessionToken);
  void notifyRoundStart (String gameToken, int roundNumber, String sessionToken);
  void notifyRoundEnd (String gameToken, String sessionToken, String winnerName, String secretWord);
  void notifyGameEnd (String gameToken, String sessionToken, String result);
} // interface GameCallBackServiceOperations
