package PlayerCallBackIDL;


/**
* PlayerCallBackIDL/GameCallBackService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Wednesday, May 7, 2025 8:53:42 AM CST
*/


// Callbacks for game events
public interface GameCallBackService extends GameCallBackServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameCallBackService
