package PlayerCallBackIDL;

/**
* PlayerCallBackIDL/GameCallBackServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Thursday, May 8, 2025 9:36:15 PM SGT
*/


// Callbacks for game events
public final class GameCallBackServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerCallBackIDL.GameCallBackService value = null;

  public GameCallBackServiceHolder ()
  {
  }

  public GameCallBackServiceHolder (PlayerCallBackIDL.GameCallBackService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerCallBackIDL.GameCallBackServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerCallBackIDL.GameCallBackServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerCallBackIDL.GameCallBackServiceHelper.type ();
  }

}
