package PlayerCallBackIDL;


/**
* PlayerCallBackIDL/LoginCallbackServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Wednesday, May 7, 2025 8:53:42 AM CST
*/


// Callback that the server uses to forceâ¬ýlogout a player
public interface LoginCallbackServiceOperations 
{
  void notifyForcedLogout (int playerID, String sessionToken) throws PlayerCallBackIDL.NotLoggedInException;
} // interface LoginCallbackServiceOperations
