package PlayerCallBackIDL;

/**
* PlayerCallBackIDL/LoginCallbackServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Thursday, May 8, 2025 9:36:15 PM SGT
*/


// Callback that the server uses to forceâ¬ýlogout a player
public final class LoginCallbackServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerCallBackIDL.LoginCallbackService value = null;

  public LoginCallbackServiceHolder ()
  {
  }

  public LoginCallbackServiceHolder (PlayerCallBackIDL.LoginCallbackService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerCallBackIDL.LoginCallbackServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerCallBackIDL.LoginCallbackServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerCallBackIDL.LoginCallbackServiceHelper.type ();
  }

}
