package PlayerCallBackIDL;


/**
* PlayerCallBackIDL/LoginCallbackServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Wednesday, May 7, 2025 8:53:42 AM CST
*/


// Callback that the server uses to forceâ¬ýlogout a player
public abstract class LoginCallbackServicePOA extends org.omg.PortableServer.Servant
 implements PlayerCallBackIDL.LoginCallbackServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notifyForcedLogout", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PlayerCallBackIDL/LoginCallbackService/notifyForcedLogout
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           this.notifyForcedLogout (playerID, sessionToken);
           out = $rh.createReply();
         } catch (PlayerCallBackIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           PlayerCallBackIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PlayerCallBackIDL/LoginCallbackService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LoginCallbackService _this() 
  {
    return LoginCallbackServiceHelper.narrow(
    super._this_object());
  }

  public LoginCallbackService _this(org.omg.CORBA.ORB orb) 
  {
    return LoginCallbackServiceHelper.narrow(
    super._this_object(orb));
  }


} // class LoginCallbackServicePOA
