package PlayerCallBackIDL;


/**
* PlayerCallBackIDL/NotLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Thursday, May 8, 2025 9:36:15 PM SGT
*/

public final class NotLoggedInException extends org.omg.CORBA.UserException
{

  public NotLoggedInException ()
  {
    super(NotLoggedInExceptionHelper.id());
  } // ctor


  public NotLoggedInException (String $reason)
  {
    super(NotLoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NotLoggedInException
