package PlayerCallBackIDL;


/**
* PlayerCallBackIDL/WaitingRoomGameCallbackServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Thursday, May 8, 2025 9:36:15 PM SGT
*/

public interface WaitingRoomGameCallbackServiceOperations 
{

  // A new player has joined the lobby; totalPlayers is the current count
  void notifyPlayerJoined (String gameToken, int totalPlayers, String sessionToken) throws PlayerCallBackIDL.NotLoggedInException;

  // Time to start the synchronized countdown
  void notifyCountdownStart (String gameToken, int countdownSeconds, String sessionToken) throws PlayerCallBackIDL.NotLoggedInException;

  // Countdown aborted/reset because someone left
  void notifyCountdownReset (String gameToken, String sessionToken) throws PlayerCallBackIDL.NotLoggedInException;
} // interface WaitingRoomGameCallbackServiceOperations
