package PlayerCallBackIDL;


/**
* PlayerCallBackIDL/WaitingRoomGameCallbackService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Thursday, May 8, 2025 9:36:15 PM SGT
*/

public interface WaitingRoomGameCallbackService extends WaitingRoomGameCallbackServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WaitingRoomGameCallbackService
