package PlayerCallBackIDL;


/**
* PlayerCallBackIDL/WaitingRoomGameCallbackServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Thursday, May 8, 2025 9:36:15 PM SGT
*/

abstract public class WaitingRoomGameCallbackServiceHelper
{
  private static String  _id = "IDL:PlayerCallBackIDL/WaitingRoomGameCallbackService:1.0";

  public static void insert (org.omg.CORBA.Any a, PlayerCallBackIDL.WaitingRoomGameCallbackService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PlayerCallBackIDL.WaitingRoomGameCallbackService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PlayerCallBackIDL.WaitingRoomGameCallbackServiceHelper.id (), "WaitingRoomGameCallbackService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PlayerCallBackIDL.WaitingRoomGameCallbackService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_WaitingRoomGameCallbackServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PlayerCallBackIDL.WaitingRoomGameCallbackService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PlayerCallBackIDL.WaitingRoomGameCallbackService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PlayerCallBackIDL.WaitingRoomGameCallbackService)
      return (PlayerCallBackIDL.WaitingRoomGameCallbackService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PlayerCallBackIDL._WaitingRoomGameCallbackServiceStub stub = new PlayerCallBackIDL._WaitingRoomGameCallbackServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PlayerCallBackIDL.WaitingRoomGameCallbackService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PlayerCallBackIDL.WaitingRoomGameCallbackService)
      return (PlayerCallBackIDL.WaitingRoomGameCallbackService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PlayerCallBackIDL._WaitingRoomGameCallbackServiceStub stub = new PlayerCallBackIDL._WaitingRoomGameCallbackServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
