package PlayerCallBackIDL;


/**
* PlayerCallBackIDL/WaitingRoomGameCallbackService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Wednesday, May 7, 2025 8:53:42 AM CST
*/

public interface WaitingRoomGameCallbackService extends WaitingRoomGameCallbackServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WaitingRoomGameCallbackService
