package PlayerCallBackIDL;

/**
* PlayerCallBackIDL/WaitingRoomGameCallbackServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerCallBack.idl
* Wednesday, May 7, 2025 8:53:42 AM CST
*/

public final class WaitingRoomGameCallbackServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerCallBackIDL.WaitingRoomGameCallbackService value = null;

  public WaitingRoomGameCallbackServiceHolder ()
  {
  }

  public WaitingRoomGameCallbackServiceHolder (PlayerCallBackIDL.WaitingRoomGameCallbackService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerCallBackIDL.WaitingRoomGameCallbackServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerCallBackIDL.WaitingRoomGameCallbackServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerCallBackIDL.WaitingRoomGameCallbackServiceHelper.type ();
  }

}
