module GameApp {
    typedef sequence<string> StringList;

    struct Player {
        long playerID;
        string fullName;
        string username;
        long gameWins;
    };

    struct Round {
        long gameID;
        StringList playersData; // "PattyCat-1" muna as of now
        long wordLength;
        long roundNumber;
    };

    // Exceptions
    exception AuthenticationException {};
    exception AlreadyLoggedInException {};
    exception NoPlayersAvailableException {};
    exception GameTimeoutException {};
    exception GameNotFoundException {};
    exception MaxAttemptsReachedException {};


    // interface for authentication the login and logout
    interface AuthService {
        //using the player object
        Player login(in string username, in string password) raises(AuthenticationException, AlreadyLoggedInException);
        void logout(in long pid);
    };

    interface GameService {
        // starts the game session
        long startGame(in long playerID) raises(NoPlayersAvailableException, GameTimeoutException);

        // start the round
        Round startRound(in long gid) raises(GameNotFoundException);

        // Randomly selects word from the words.txt file
        string getRandomWord();

        //Calls the getWordLength method
        //Can be accessed by the client
        //Return the number of letters in the mystery word
        //Number of letters same number of underline (yung eto _ _ _ )
        long getWordLength(in string word);

        // contains the guessed letters of the player??
        // Processes the player’s guessed letter and updates game state.
        long guessLetter(in long playerID, in char letter) raises(MaxAttemptsReachedException, GameNotFoundException);

        // return the underline state or the current state of the underlined letters
        // return the underlined word with correctly guesses letters revealed
        string getCurrentLetterState(in long playerID);

        // returns the remaining attempts
        long getRemainingAttempts(in long playerID);

        long getRemainingWaitingTime() raises(GameTimeoutException);
        long getRemainingRoundTime(in long gid) raises(GameTimeoutException);

        boolean isGameOver(in long playerID);
        boolean hasWon(in long playerID);
        string getRoundWinner(in long gid);
        string getGameWinner(in long gid);
        void leaveGame(in long pid, in long gid);

        //StringList getLeaderboards();
    };
};