module PlayerGame {
    typedef sequence<string> StringList;
    typedef sequence<long> IndexList;

    struct Player {
        long playerID;
        string fullName;
        string username;
        long gameWins;
    };

    struct Round {
        long gameID;
        StringList playersData;
        long wordLength;
        long roundNumber;
    };

    // Exceptions
    exception AuthenticationException {};
    exception AlreadyLoggedInException {};
    exception NoPlayersAvailableException {};
    exception GameTimeoutException {};
    exception GameNotFoundException {};
    exception MaxAttemptsReachedException {};
    exception AlreadyGuessedLetterException {};
    exception NotLoggedInException {};

    // interface for authentication: login and logout
    interface AuthService {
        // Login returns playerID and sessionToken
        string login(in string username, in string password, out long playerID)
            raises(AuthenticationException, AlreadyLoggedInException);

        void logout(in long playerID, in string sessionToken)
            raises(NotLoggedInException);
    };

    interface GameService {
        // Starts the game session
        long startGame(in long playerID, in string sessionToken)
            raises(NoPlayersAvailableException, GameTimeoutException, NotLoggedInException);

        // Starts the round
        Round startRound(in long gameID, in long playerID, in string sessionToken)
            raises(GameNotFoundException, NotLoggedInException);

        // Randomly selects a word it is only called when the round ends
        string getRandomWord(in long gameID, in long roundNumber, in long playerID, in string sessionToken)
            raises(GameNotFoundException, NotLoggedInException);

        // Processes the player’s guessed letter and returns indexes of correctly guessed positions
        IndexList guessLetter(in long playerID, in string sessionToken, in char letter)
            raises(MaxAttemptsReachedException, GameNotFoundException, AlreadyGuessedLetterException, NotLoggedInException);

        // Returns the number of remaining attempts
        long getRemainingAttempts(in long playerID, in string sessionToken)
            raises(NotLoggedInException);

        // Uses threads to manage waiting time and round time
        long getRemainingWaitingTime(in long playerID, in string sessionToken)
            raises(GameTimeoutException, NotLoggedInException);

        long getRemainingRoundTime(in long gameID, in long playerID, in string sessionToken)
            raises(GameTimeoutException, NotLoggedInException);

        // Game state methods
        boolean isGameOver(in long playerID, in string sessionToken)
            raises(NotLoggedInException);

        string getRoundWinner(in long gameID, in long playerID, in string sessionToken)
            raises(NotLoggedInException);

        string getGameWinner(in long gameID, in long playerID, in string sessionToken)
            raises(NotLoggedInException);

        // Player leaves the game
        void leaveGame(in long playerID, in string sessionToken, in long gameID)
            raises(NotLoggedInException);

        // Gets the leaderboard
        StringList getLeaderboards(in long playerID, in string sessionToken)
            raises(NotLoggedInException);
    };

};
