package Server_Java.idls.AuthenticationIDL;


import Server_Java.idls.PlayerCallBackIDL.LoginCallbackService;
import Server_Java.idls.PlayerCallBackIDL.LoginCallbackServiceHelper;

/**
* AuthenticationIDL/_AuthenticationServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Tuesday, April 29, 2025 5:49:16 PM CST
*/

public class _AuthenticationServiceStub extends org.omg.CORBA.portable.ObjectImpl implements AuthenticationService
{


  // Player login: client hands us its callback servant
  public String login (String username, String password, org.omg.CORBA.IntHolder playerID, LoginCallbackService cb) throws AuthenticationException, AlreadyLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("login", true);
                $out.write_string (username);
                $out.write_string (password);
                LoginCallbackServiceHelper.write ($out, cb);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                playerID.value = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AuthenticationIDL/AuthenticationException:1.0"))
                    throw AuthenticationExceptionHelper.read ($in);
                else if (_id.equals ("IDL:AuthenticationIDL/AlreadyLoggedInException:1.0"))
                    throw AlreadyLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return login (username, password, playerID, cb        );
            } finally {
                _releaseReply ($in);
            }
  } // login


  // Player logout using session token
  public void logout (int playerID, String sessionToken) throws NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("logout", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AuthenticationIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                logout (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // logout


  // Admin login (no callback needed)
  public String adminLogin (String username, String password, org.omg.CORBA.IntHolder adminID) throws AuthenticationException, AlreadyLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("adminLogin", true);
                $out.write_string (username);
                $out.write_string (password);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                adminID.value = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AuthenticationIDL/AuthenticationException:1.0"))
                    throw AuthenticationExceptionHelper.read ($in);
                else if (_id.equals ("IDL:AuthenticationIDL/AlreadyLoggedInException:1.0"))
                    throw AlreadyLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return adminLogin (username, password, adminID        );
            } finally {
                _releaseReply ($in);
            }
  } // adminLogin


  // Admin logout
  public void adminLogout (int adminID, String sessionToken) throws NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("adminLogout", true);
                $out.write_long (adminID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AuthenticationIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                adminLogout (adminID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // adminLogout

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AuthenticationIDL/AuthenticationService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "AuthenticationIDL._AuthenticationServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AuthenticationServiceStub
