package Server_Java.idls.AuthenticationIDL;

/**
* Server_Java.idls.AuthenticationIDL/AlreadyLoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Wednesday, April 30, 2025 12:18:04 AM CST
*/

public final class AlreadyLoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Java.idls.AuthenticationIDL.AlreadyLoggedInException value = null;

  public AlreadyLoggedInExceptionHolder ()
  {
  }

  public AlreadyLoggedInExceptionHolder (Server_Java.idls.AuthenticationIDL.AlreadyLoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Java.idls.AuthenticationIDL.AlreadyLoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Java.idls.AuthenticationIDL.AlreadyLoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Java.idls.AuthenticationIDL.AlreadyLoggedInExceptionHelper.type ();
  }

}
