package Server_Java.idls.AuthenticationIDL;


/**
* AuthenticationIDL/AlreadyLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Tuesday, April 29, 2025 5:49:16 PM CST
*/

public final class AlreadyLoggedInException extends org.omg.CORBA.UserException
{

  public AlreadyLoggedInException ()
  {
    super(AlreadyLoggedInExceptionHelper.id());
  } // ctor


  public AlreadyLoggedInException (String $reason)
  {
    super(AlreadyLoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyLoggedInException
