package Server_Java.idls.AuthenticationIDL;


/**
* Server_Java.idls.AuthenticationIDL/AlreadyLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Wednesday, April 30, 2025 12:18:04 AM CST
*/

public final class AlreadyLoggedInException extends org.omg.CORBA.UserException
{

  public AlreadyLoggedInException ()
  {
    super(AlreadyLoggedInExceptionHelper.id());
  } // ctor


  public AlreadyLoggedInException (String $reason)
  {
    super(AlreadyLoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyLoggedInException
