package Server_Java.idls.AuthenticationIDL;


/**
* Server_Java.idls.AuthenticationIDL/AuthenticationException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Wednesday, April 30, 2025 12:18:04 AM CST
*/

public final class AuthenticationException extends org.omg.CORBA.UserException
{

  public AuthenticationException ()
  {
    super(AuthenticationExceptionHelper.id());
  } // ctor


  public AuthenticationException (String $reason)
  {
    super(AuthenticationExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AuthenticationException
