package Server_Java.idls.AuthenticationIDL;


/**
* AuthenticationIDL/AuthenticationServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Tuesday, April 29, 2025 5:49:16 PM CST
*/

abstract public class AuthenticationServiceHelper
{
  private static String  _id = "IDL:AuthenticationIDL/AuthenticationService:1.0";

  public static void insert (org.omg.CORBA.Any a, AuthenticationService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AuthenticationService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AuthenticationServiceHelper.id (), "AuthenticationService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AuthenticationService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AuthenticationServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AuthenticationService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AuthenticationService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AuthenticationService)
      return (AuthenticationService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AuthenticationServiceStub stub = new _AuthenticationServiceStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AuthenticationService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AuthenticationService)
      return (AuthenticationService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AuthenticationServiceStub stub = new _AuthenticationServiceStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
