package Server_Java.idls.AuthenticationIDL;

/**
* AuthenticationIDL/AuthenticationExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Tuesday, April 29, 2025 5:49:16 PM CST
*/

public final class AuthenticationExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AuthenticationException value = null;

  public AuthenticationExceptionHolder ()
  {
  }

  public AuthenticationExceptionHolder (AuthenticationException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuthenticationExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuthenticationExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuthenticationExceptionHelper.type ();
  }

}
