package Server_Java.idls.AuthenticationIDL;

/**
* AuthenticationIDL/AuthenticationServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Tuesday, April 29, 2025 5:49:16 PM CST
*/

public final class AuthenticationServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public AuthenticationService value = null;

  public AuthenticationServiceHolder ()
  {
  }

  public AuthenticationServiceHolder (AuthenticationService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuthenticationServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuthenticationServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuthenticationServiceHelper.type ();
  }

}
