package Server_Java.idls.AuthenticationIDL;


/**
* Server_Java.idls.AuthenticationIDL/AuthenticationService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Wednesday, April 30, 2025 12:18:04 AM CST
*/

public interface AuthenticationService extends AuthenticationServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuthenticationService
