package Server_Java.idls.AuthenticationIDL;


/**
* Server_Java.idls.AuthenticationIDL/AuthenticationServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Wednesday, April 30, 2025 12:18:04 AM CST
*/

public abstract class AuthenticationServicePOA extends org.omg.PortableServer.Servant
 implements Server_Java.idls.AuthenticationIDL.AuthenticationServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("logout", new java.lang.Integer (1));
    _methods.put ("adminLogin", new java.lang.Integer (2));
    _methods.put ("adminLogout", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Player login: client hands us its callback servant
       case 0:  // Server_Java.idls.AuthenticationIDL/AuthenticationService/login
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           org.omg.CORBA.IntHolder playerID = new org.omg.CORBA.IntHolder ();
           Server_Java.idls.PlayerCallBackIDL.LoginCallbackService cb = Server_Java.idls.PlayerCallBackIDL.LoginCallbackServiceHelper.read (in);
           String $result = null;
           $result = this.login (username, password, playerID, cb);
           out = $rh.createReply();
           out.write_string ($result);
           out.write_long (playerID.value);
         } catch (Server_Java.idls.AuthenticationIDL.AuthenticationException $ex) {
           out = $rh.createExceptionReply ();
           Server_Java.idls.AuthenticationIDL.AuthenticationExceptionHelper.write (out, $ex);
         } catch (Server_Java.idls.AuthenticationIDL.AlreadyLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server_Java.idls.AuthenticationIDL.AlreadyLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Player logout using session token
       case 1:  // Server_Java.idls.AuthenticationIDL/AuthenticationService/logout
       {
         try {
           int playerID = in.read_long ();
           String sessionToken = in.read_string ();
           this.logout (playerID, sessionToken);
           out = $rh.createReply();
         } catch (Server_Java.idls.AuthenticationIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server_Java.idls.AuthenticationIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Admin login (no callback needed)
       case 2:  // Server_Java.idls.AuthenticationIDL/AuthenticationService/adminLogin
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           org.omg.CORBA.IntHolder adminID = new org.omg.CORBA.IntHolder ();
           String $result = null;
           $result = this.adminLogin (username, password, adminID);
           out = $rh.createReply();
           out.write_string ($result);
           out.write_long (adminID.value);
         } catch (Server_Java.idls.AuthenticationIDL.AuthenticationException $ex) {
           out = $rh.createExceptionReply ();
           Server_Java.idls.AuthenticationIDL.AuthenticationExceptionHelper.write (out, $ex);
         } catch (Server_Java.idls.AuthenticationIDL.AlreadyLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server_Java.idls.AuthenticationIDL.AlreadyLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Admin logout
       case 3:  // Server_Java.idls.AuthenticationIDL/AuthenticationService/adminLogout
       {
         try {
           int adminID = in.read_long ();
           String sessionToken = in.read_string ();
           this.adminLogout (adminID, sessionToken);
           out = $rh.createReply();
         } catch (Server_Java.idls.AuthenticationIDL.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           Server_Java.idls.AuthenticationIDL.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Server_Java.idls.AuthenticationIDL/AuthenticationService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AuthenticationService _this() 
  {
    return AuthenticationServiceHelper.narrow(
    super._this_object());
  }

  public AuthenticationService _this(org.omg.CORBA.ORB orb) 
  {
    return AuthenticationServiceHelper.narrow(
    super._this_object(orb));
  }


} // class AuthenticationServicePOA
