package Server_Java.idls.AuthenticationIDL;


/**
* AuthenticationIDL/AuthenticationService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Tuesday, April 29, 2025 5:49:16 PM CST
*/

public interface AuthenticationService extends AuthenticationServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface AuthenticationService
