package Server_Java.idls.AuthenticationIDL;

/**
* Server_Java.idls.AuthenticationIDL/NotLoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Authentication.idl
* Wednesday, April 30, 2025 12:18:04 AM CST
*/

public final class NotLoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Java.idls.AuthenticationIDL.NotLoggedInException value = null;

  public NotLoggedInExceptionHolder ()
  {
  }

  public NotLoggedInExceptionHolder (Server_Java.idls.AuthenticationIDL.NotLoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Java.idls.AuthenticationIDL.NotLoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Java.idls.AuthenticationIDL.NotLoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Java.idls.AuthenticationIDL.NotLoggedInExceptionHelper.type ();
  }

}
