package GameApp;


/**
* GameApp/AuthenticationException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameApp.idl
* Monday, April 7, 2025 11:07:32 PM CST
*/

public final class AuthenticationException extends org.omg.CORBA.UserException
{

  public AuthenticationException ()
  {
    super(AuthenticationExceptionHelper.id());
  } // ctor


  public AuthenticationException (String $reason)
  {
    super(AuthenticationExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AuthenticationException
