package GameApp;

/**
* GameApp/AuthServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameApp.idl
* Monday, April 7, 2025 11:07:32 PM CST
*/

public final class AuthServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApp.AuthService value = null;

  public AuthServiceHolder ()
  {
  }

  public AuthServiceHolder (GameApp.AuthService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApp.AuthServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApp.AuthServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApp.AuthServiceHelper.type ();
  }

}
