package GameApp;


/**
* GameApp/AuthServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameApp.idl
* Monday, April 7, 2025 11:07:32 PM CST
*/

public interface AuthServiceOperations 
{
  GameApp.Player login (String username, String password) throws GameApp.AuthenticationException, GameApp.AlreadyLoggedInException;
  void logout (int pid);
} // interface AuthServiceOperations
