package GameApp;


/**
* GameApp/GameNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameApp.idl
* Monday, April 7, 2025 11:07:32 PM CST
*/

public final class GameNotFoundException extends org.omg.CORBA.UserException
{

  public GameNotFoundException ()
  {
    super(GameNotFoundExceptionHelper.id());
  } // ctor


  public GameNotFoundException (String $reason)
  {
    super(GameNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class GameNotFoundException
