package GameApp;

/**
* GameApp/GameNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameApp.idl
* Monday, April 7, 2025 11:07:32 PM CST
*/

public final class GameNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApp.GameNotFoundException value = null;

  public GameNotFoundExceptionHolder ()
  {
  }

  public GameNotFoundExceptionHolder (GameApp.GameNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApp.GameNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApp.GameNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApp.GameNotFoundExceptionHelper.type ();
  }

}
