package GameApp;

/**
* GameApp/GameTimeoutExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameApp.idl
* Monday, April 7, 2025 11:07:32 PM CST
*/

public final class GameTimeoutExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApp.GameTimeoutException value = null;

  public GameTimeoutExceptionHolder ()
  {
  }

  public GameTimeoutExceptionHolder (GameApp.GameTimeoutException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApp.GameTimeoutExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApp.GameTimeoutExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApp.GameTimeoutExceptionHelper.type ();
  }

}
