package GameApp;

/**
* GameApp/MaxAttemptsReachedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameApp.idl
* Monday, April 7, 2025 11:07:32 PM CST
*/

public final class MaxAttemptsReachedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApp.MaxAttemptsReachedException value = null;

  public MaxAttemptsReachedExceptionHolder ()
  {
  }

  public MaxAttemptsReachedExceptionHolder (GameApp.MaxAttemptsReachedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApp.MaxAttemptsReachedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApp.MaxAttemptsReachedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApp.MaxAttemptsReachedExceptionHelper.type ();
  }

}
