package GameApp;

/**
* GameApp/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameApp.idl
* Monday, April 7, 2025 11:07:32 PM CST
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApp.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (GameApp.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApp.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApp.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApp.PlayerHelper.type ();
  }

}
