package GameApp;


/**
* GameApp/Player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameApp.idl
* Monday, April 7, 2025 11:07:32 PM CST
*/

public final class Player implements org.omg.CORBA.portable.IDLEntity
{
  public int playerID = (int)0;
  public String fullName = null;
  public String username = null;
  public int gameWins = (int)0;

  public Player ()
  {
  } // ctor

  public Player (int _playerID, String _fullName, String _username, int _gameWins)
  {
    playerID = _playerID;
    fullName = _fullName;
    username = _username;
    gameWins = _gameWins;
  } // ctor

} // class Player
