package GameApp;


/**
* GameApp/Round.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameApp.idl
* Monday, April 7, 2025 11:07:32 PM CST
*/

public final class Round implements org.omg.CORBA.portable.IDLEntity
{
  public int gameID = (int)0;
  public String playersData[] = null;

  // "PattyCat-1" muna as of now
  public int wordLength = (int)0;
  public int roundNumber = (int)0;

  public Round ()
  {
  } // ctor

  public Round (int _gameID, String[] _playersData, int _wordLength, int _roundNumber)
  {
    gameID = _gameID;
    playersData = _playersData;
    wordLength = _wordLength;
    roundNumber = _roundNumber;
  } // ctor

} // class Round
