package GameApp;

/**
* GameApp/RoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameApp.idl
* Monday, April 7, 2025 11:07:32 PM CST
*/

public final class RoundHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApp.Round value = null;

  public RoundHolder ()
  {
  }

  public RoundHolder (GameApp.Round initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApp.RoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApp.RoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApp.RoundHelper.type ();
  }

}
