package AuthenticationIDL;


/**
* AuthenticationIDL/AlreadyLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Wednesday, May 7, 2025 9:31:54 AM CST
*/

public final class AlreadyLoggedInException extends org.omg.CORBA.UserException
{

  public AlreadyLoggedInException ()
  {
    super(AlreadyLoggedInExceptionHelper.id());
  } // ctor


  public AlreadyLoggedInException (String $reason)
  {
    super(AlreadyLoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyLoggedInException
