package AuthenticationIDL;

/**
* AuthenticationIDL/AuthenticationExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Wednesday, May 7, 2025 9:31:54 AM CST
*/

public final class AuthenticationExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AuthenticationIDL.AuthenticationException value = null;

  public AuthenticationExceptionHolder ()
  {
  }

  public AuthenticationExceptionHolder (AuthenticationIDL.AuthenticationException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuthenticationIDL.AuthenticationExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuthenticationIDL.AuthenticationExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuthenticationIDL.AuthenticationExceptionHelper.type ();
  }

}
