package AuthenticationIDL;

/**
* AuthenticationIDL/AuthenticationServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Wednesday, May 7, 2025 9:31:54 AM CST
*/

public final class AuthenticationServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public AuthenticationIDL.AuthenticationService value = null;

  public AuthenticationServiceHolder ()
  {
  }

  public AuthenticationServiceHolder (AuthenticationIDL.AuthenticationService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuthenticationIDL.AuthenticationServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuthenticationIDL.AuthenticationServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuthenticationIDL.AuthenticationServiceHelper.type ();
  }

}
