package AuthenticationIDL;


/**
* AuthenticationIDL/AuthenticationException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Wednesday, May 7, 2025 9:31:54 AM CST
*/

public final class AuthenticationException extends org.omg.CORBA.UserException
{
  public String message = null;

  public AuthenticationException ()
  {
    super(AuthenticationExceptionHelper.id());
  } // ctor

  public AuthenticationException (String _message)
  {
    super(AuthenticationExceptionHelper.id());
    message = _message;
  } // ctor


  public AuthenticationException (String $reason, String _message)
  {
    super(AuthenticationExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class AuthenticationException
