package AuthenticationIDL;


/**
* AuthenticationIDL/AuthenticationService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Authentication.idl
* Wednesday, May 7, 2025 9:31:54 AM CST
*/

public interface AuthenticationService extends AuthenticationServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuthenticationService
