package AdminIDL;


/**
* AdminIDL/_AdminServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, May 13, 2025 10:37:10 PM CST
*/

public class _AdminServiceStub extends org.omg.CORBA.portable.ObjectImpl implements AdminIDL.AdminService
{


  // Create a new player account
  public void createPlayer (String fullname, String username, String password, String sessionToken, int adminID) throws AdminIDL.AccountExistsException, AdminIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createPlayer", true);
                $out.write_string (fullname);
                $out.write_string (username);
                $out.write_string (password);
                $out.write_string (sessionToken);
                $out.write_long (adminID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AdminIDL/AccountExistsException:1.0"))
                    throw AdminIDL.AccountExistsExceptionHelper.read ($in);
                else if (_id.equals ("IDL:AdminIDL/NotLoggedInException:1.0"))
                    throw AdminIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                createPlayer (fullname, username, password, sessionToken, adminID        );
            } finally {
                _releaseReply ($in);
            }
  } // createPlayer


  // View list of player's account
  public String[] viewPlayers (String sessionToken, int adminID) throws AdminIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("viewPlayers", true);
                $out.write_string (sessionToken);
                $out.write_long (adminID);
                $in = _invoke ($out);
                String $result[] = AdminIDL.StringListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AdminIDL/NotLoggedInException:1.0"))
                    throw AdminIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return viewPlayers (sessionToken, adminID        );
            } finally {
                _releaseReply ($in);
            }
  } // viewPlayers


  // Modify existing player's password
  public void modifyPlayer (int playerID, String newPassword, String sessionToken, int adminID) throws AdminIDL.AccountNotFoundException, AdminIDL.ExistingPasswordException, AdminIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modifyPlayer", true);
                $out.write_long (playerID);
                $out.write_string (newPassword);
                $out.write_string (sessionToken);
                $out.write_long (adminID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AdminIDL/AccountNotFoundException:1.0"))
                    throw AdminIDL.AccountNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:AdminIDL/ExistingPasswordException:1.0"))
                    throw AdminIDL.ExistingPasswordExceptionHelper.read ($in);
                else if (_id.equals ("IDL:AdminIDL/NotLoggedInException:1.0"))
                    throw AdminIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                modifyPlayer (playerID, newPassword, sessionToken, adminID        );
            } finally {
                _releaseReply ($in);
            }
  } // modifyPlayer


  // Delete player account
  public void deletePlayer (int playerID, String sessionToken, int adminID) throws AdminIDL.AccountNotFoundException, AdminIDL.AccountCurrentlyActiveException, AdminIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deletePlayer", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $out.write_long (adminID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AdminIDL/AccountNotFoundException:1.0"))
                    throw AdminIDL.AccountNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:AdminIDL/AccountCurrentlyActiveException:1.0"))
                    throw AdminIDL.AccountCurrentlyActiveExceptionHelper.read ($in);
                else if (_id.equals ("IDL:AdminIDL/NotLoggedInException:1.0"))
                    throw AdminIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                deletePlayer (playerID, sessionToken, adminID        );
            } finally {
                _releaseReply ($in);
            }
  } // deletePlayer


  // Search for a player by username
  public String[] searchPlayers (String query, String sessionToken, int adminID) throws AdminIDL.NotLoggedInException, AdminIDL.PlayerNotFoundException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("searchPlayers", true);
                $out.write_string (query);
                $out.write_string (sessionToken);
                $out.write_long (adminID);
                $in = _invoke ($out);
                String $result[] = AdminIDL.StringListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AdminIDL/NotLoggedInException:1.0"))
                    throw AdminIDL.NotLoggedInExceptionHelper.read ($in);
                else if (_id.equals ("IDL:AdminIDL/PlayerNotFoundException:1.0"))
                    throw AdminIDL.PlayerNotFoundExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return searchPlayers (query, sessionToken, adminID        );
            } finally {
                _releaseReply ($in);
            }
  } // searchPlayers


  // Get the current game waiting time
  public int getCurrentWaitingTime (String sessionToken, int adminID) throws AdminIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCurrentWaitingTime", true);
                $out.write_string (sessionToken);
                $out.write_long (adminID);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AdminIDL/NotLoggedInException:1.0"))
                    throw AdminIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCurrentWaitingTime (sessionToken, adminID        );
            } finally {
                _releaseReply ($in);
            }
  } // getCurrentWaitingTime


  // Get the current game round duration
  public int getCurrentRoundDuration (String sessionToken, int adminID) throws AdminIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCurrentRoundDuration", true);
                $out.write_string (sessionToken);
                $out.write_long (adminID);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AdminIDL/NotLoggedInException:1.0"))
                    throw AdminIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCurrentRoundDuration (sessionToken, adminID        );
            } finally {
                _releaseReply ($in);
            }
  } // getCurrentRoundDuration


  // Change waiting time before game starts
  public void modifyWaitingTime (int waitTime, String sessionToken, int adminID) throws AdminIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modifyWaitingTime", true);
                $out.write_long (waitTime);
                $out.write_string (sessionToken);
                $out.write_long (adminID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AdminIDL/NotLoggedInException:1.0"))
                    throw AdminIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                modifyWaitingTime (waitTime, sessionToken, adminID        );
            } finally {
                _releaseReply ($in);
            }
  } // modifyWaitingTime


  // Change time duration for each round
  public void modifyRoundDuration (int roundTime, String sessionToken, int adminID) throws AdminIDL.NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modifyRoundDuration", true);
                $out.write_long (roundTime);
                $out.write_string (sessionToken);
                $out.write_long (adminID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AdminIDL/NotLoggedInException:1.0"))
                    throw AdminIDL.NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                modifyRoundDuration (roundTime, sessionToken, adminID        );
            } finally {
                _releaseReply ($in);
            }
  } // modifyRoundDuration

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AdminIDL/AdminService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "AdminIDL._AdminServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AdminServiceStub
