package AdminIDL;

/**
* AdminIDL/AccountCurrentlyActiveExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Sunday, May 11, 2025 7:25:35 AM CST
*/

public final class AccountCurrentlyActiveExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminIDL.AccountCurrentlyActiveException value = null;

  public AccountCurrentlyActiveExceptionHolder ()
  {
  }

  public AccountCurrentlyActiveExceptionHolder (AdminIDL.AccountCurrentlyActiveException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminIDL.AccountCurrentlyActiveExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminIDL.AccountCurrentlyActiveExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminIDL.AccountCurrentlyActiveExceptionHelper.type ();
  }

}
