package AdminIDL;


/**
* AdminIDL/AccountExistsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Sunday, May 11, 2025 7:25:35 AM CST
*/

public final class AccountExistsException extends org.omg.CORBA.UserException
{

  public AccountExistsException ()
  {
    super(AccountExistsExceptionHelper.id());
  } // ctor


  public AccountExistsException (String $reason)
  {
    super(AccountExistsExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccountExistsException
