package AdminIDL;

/**
* AdminIDL/AccountNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Saturday, May 10, 2025 1:42:31 AM CST
*/

public final class AccountNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminIDL.AccountNotFoundException value = null;

  public AccountNotFoundExceptionHolder ()
  {
  }

  public AccountNotFoundExceptionHolder (AdminIDL.AccountNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminIDL.AccountNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminIDL.AccountNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminIDL.AccountNotFoundExceptionHelper.type ();
  }

}
