package AdminIDL;


/**
* AdminIDL/AccountCurrentlyActiveException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, May 13, 2025 10:37:10 PM CST
*/

public final class AccountCurrentlyActiveException extends org.omg.CORBA.UserException
{

  public AccountCurrentlyActiveException ()
  {
    super(AccountCurrentlyActiveExceptionHelper.id());
  } // ctor


  public AccountCurrentlyActiveException (String $reason)
  {
    super(AccountCurrentlyActiveExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccountCurrentlyActiveException
