package AdminIDL;


/**
* AdminIDL/AccountCurrentlyActiveException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Sunday, May 11, 2025 7:25:35 AM CST
*/

public final class AccountCurrentlyActiveException extends org.omg.CORBA.UserException
{

  public AccountCurrentlyActiveException ()
  {
    super(AccountCurrentlyActiveExceptionHelper.id());
  } // ctor


  public AccountCurrentlyActiveException (String $reason)
  {
    super(AccountCurrentlyActiveExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccountCurrentlyActiveException
