package AdminIDL;

/**
* AdminIDL/AccountExistsExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Wednesday, May 7, 2025 8:53:01 AM CST
*/

public final class AccountExistsExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminIDL.AccountExistsException value = null;

  public AccountExistsExceptionHolder ()
  {
  }

  public AccountExistsExceptionHolder (AdminIDL.AccountExistsException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminIDL.AccountExistsExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminIDL.AccountExistsExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminIDL.AccountExistsExceptionHelper.type ();
  }

}
