package AdminIDL;


/**
* AdminIDL/AccountNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, May 13, 2025 10:37:10 PM CST
*/

public final class AccountNotFoundException extends org.omg.CORBA.UserException
{

  public AccountNotFoundException ()
  {
    super(AccountNotFoundExceptionHelper.id());
  } // ctor


  public AccountNotFoundException (String $reason)
  {
    super(AccountNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccountNotFoundException
