package AdminIDL;


/**
* AdminIDL/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Saturday, May 10, 2025 1:42:31 AM CST
*/

public interface AdminServiceOperations 
{

  // Create a new player account
  void createPlayer (String fullname, String username, String password, String sessionToken, int adminID) throws AdminIDL.AccountExistsException, AdminIDL.NotLoggedInException;

  // Modify existing player's password
  void modifyPlayer (int playerID, String newPassword, String sessionToken, int adminID) throws AdminIDL.AccountNotFoundException, AdminIDL.ExistingPasswordException, AdminIDL.NotLoggedInException;

  // Delete player account
  void deletePlayer (int playerID, String sessionToken, int adminID) throws AdminIDL.AccountNotFoundException, AdminIDL.AccountCurrentlyActiveException, AdminIDL.NotLoggedInException;

  // Search for a player by username
  String searchPlayer (String username, String sessionToken, int adminID) throws AdminIDL.NotLoggedInException, AdminIDL.PlayerNotFoundException;

  // Get the current game waiting time
  int getCurrentWaitingTime (String sessionToken, int adminID) throws AdminIDL.NotLoggedInException;

  // Get the current game round duration
  int getCurrentRoundDuration (String sessionToken, int adminID) throws AdminIDL.NotLoggedInException;

  // Change waiting time before game starts
  void modifyWaitingTime (int waitTime, String sessionToken, int adminID) throws AdminIDL.NotLoggedInException;

  // Change time duration for each round
  void modifyRoundDuration (int roundTime, String sessionToken, int adminID) throws AdminIDL.NotLoggedInException;
} // interface AdminServiceOperations
