package AdminIDL;

/**
* AdminIDL/AdminServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Sunday, May 11, 2025 7:25:35 AM CST
*/

public final class AdminServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminIDL.AdminService value = null;

  public AdminServiceHolder ()
  {
  }

  public AdminServiceHolder (AdminIDL.AdminService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminIDL.AdminServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminIDL.AdminServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminIDL.AdminServiceHelper.type ();
  }

}
