package AdminIDL;


/**
* AdminIDL/ExistingPasswordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Sunday, May 11, 2025 7:25:35 AM CST
*/

public final class ExistingPasswordException extends org.omg.CORBA.UserException
{

  public ExistingPasswordException ()
  {
    super(ExistingPasswordExceptionHelper.id());
  } // ctor


  public ExistingPasswordException (String $reason)
  {
    super(ExistingPasswordExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class ExistingPasswordException
