package AdminIDL;

/**
* AdminIDL/ExistingPasswordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Tuesday, May 13, 2025 10:37:10 PM CST
*/

public final class ExistingPasswordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminIDL.ExistingPasswordException value = null;

  public ExistingPasswordExceptionHolder ()
  {
  }

  public ExistingPasswordExceptionHolder (AdminIDL.ExistingPasswordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminIDL.ExistingPasswordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminIDL.ExistingPasswordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminIDL.ExistingPasswordExceptionHelper.type ();
  }

}
