package AdminIDL;


/**
* AdminIDL/NotLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Sunday, May 11, 2025 7:25:35 AM CST
*/

public final class NotLoggedInException extends org.omg.CORBA.UserException
{

  public NotLoggedInException ()
  {
    super(NotLoggedInExceptionHelper.id());
  } // ctor


  public NotLoggedInException (String $reason)
  {
    super(NotLoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NotLoggedInException
