package AdminIDL;

/**
* AdminIDL/NotLoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Saturday, May 10, 2025 1:42:31 AM CST
*/

public final class NotLoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminIDL.NotLoggedInException value = null;

  public NotLoggedInExceptionHolder ()
  {
  }

  public NotLoggedInExceptionHolder (AdminIDL.NotLoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminIDL.NotLoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminIDL.NotLoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminIDL.NotLoggedInExceptionHelper.type ();
  }

}
