package AdminIDL;

/**
* AdminIDL/PlayerNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Wednesday, May 7, 2025 8:53:01 AM CST
*/

public final class PlayerNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminIDL.PlayerNotFoundException value = null;

  public PlayerNotFoundExceptionHolder ()
  {
  }

  public PlayerNotFoundExceptionHolder (AdminIDL.PlayerNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminIDL.PlayerNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminIDL.PlayerNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminIDL.PlayerNotFoundExceptionHelper.type ();
  }

}
