package Server_Java.idls.GameIDL;


import Server_Java.idls.PlayerCallBackIDL.GameCallBackService;
import Server_Java.idls.PlayerCallBackIDL.GameCallBackServiceHelper;

/**
* GameIDL/_GameServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Tuesday, April 29, 2025 5:49:19 PM CST
*/


//
public class _GameServiceStub extends org.omg.CORBA.portable.ObjectImpl implements GameService
{


  // ������ Player Authentication & Info ��������������������������������������������������������������
  public String getDisplayName (int playerID, String sessionToken) throws NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getDisplayName", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getDisplayName (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getDisplayName

  public String[] getLeaderboards (int playerID, String sessionToken) throws NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLeaderboards", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result[] = StringListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLeaderboards (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getLeaderboards


  // ������ Settings Retrieval ����������������������������������������������������������������������������������
  public void getSetting (String key, org.omg.CORBA.StringHolder value, String sessionToken) throws NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getSetting", true);
                $out.write_string (key);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                value.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getSetting (key, value, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getSetting


  // ������ Lobby Management ��������������������������������������������������������������������������������������
  public String joinLobby (int playerID, String sessionToken) throws NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("joinLobby", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return joinLobby (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // joinLobby

  public String getLobbyStatus (String sessionToken) throws NotLoggedInException, GameTimeOutException, NotEnoughPlayersException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLobbyStatus", true);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/GameTimeOutException:1.0"))
                    throw GameTimeOutExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/NotEnoughPlayersException:1.0"))
                    throw NotEnoughPlayersExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLobbyStatus (sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getLobbyStatus

  public int getNumberOfPlayersJoined (int playerID, String sessionToken) throws NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNumberOfPlayersJoined", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getNumberOfPlayersJoined (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getNumberOfPlayersJoined

  public int startGame (int playerID, String sessionToken) throws NotEnoughPlayersException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startGame", true);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotEnoughPlayersException:1.0"))
                    throw NotEnoughPlayersExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startGame (playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // startGame


  // ������ Register the client's callback servant here ��������������������������������
  public void registerCallBack (int playerID, String gameToken, String sessionToken, GameCallBackService cb) throws NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerCallBack", true);
                $out.write_long (playerID);
                $out.write_string (gameToken);
                $out.write_string (sessionToken);
                GameCallBackServiceHelper.write ($out, cb);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerCallBack (playerID, gameToken, sessionToken, cb        );
            } finally {
                _releaseReply ($in);
            }
  } // registerCallBack


  // ������ Game and Round Management ��������������������������������������������������������������������
  public int startRound (String gameToken, int roundNumber, int playerID, String sessionToken) throws GameNotFoundException, NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startRound", true);
                $out.write_string (gameToken);
                $out.write_long (roundNumber);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/GameNotFoundException:1.0"))
                    throw GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startRound (gameToken, roundNumber, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // startRound

  public String getRandomWord (String gameToken, int roundNumber, int playerID, String sessionToken) throws GameNotFoundException, NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRandomWord", true);
                $out.write_string (gameToken);
                $out.write_long (roundNumber);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/GameNotFoundException:1.0"))
                    throw GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRandomWord (gameToken, roundNumber, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRandomWord


  // ������ Letter Guessing ��������������������������������������������������������������������������������������
  public int[] guessLetter (String gameToken, int playerID, String sessionToken, char letter) throws MaxAttemptsReachedException, GameNotFoundException, AlreadyGuessedLetterException, NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("guessLetter", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $out.write_char (letter);
                $in = _invoke ($out);
                int $result[] = IndexListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/MaxAttemptsReachedException:1.0"))
                    throw MaxAttemptsReachedExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/GameNotFoundException:1.0"))
                    throw GameNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/AlreadyGuessedLetterException:1.0"))
                    throw AlreadyGuessedLetterExceptionHelper.read ($in);
                else if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return guessLetter (gameToken, playerID, sessionToken, letter        );
            } finally {
                _releaseReply ($in);
            }
  } // guessLetter


  // ������ Game and Round Results ����������������������������������������������������������������������
  public String getRoundWinner (String gameToken, int playerID, String sessionToken) throws NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRoundWinner", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRoundWinner (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getRoundWinner

  public String getGameWinner (String gameToken, int playerID, String sessionToken) throws NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getGameWinner", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getGameWinner (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getGameWinner

  public int getPlayerWins (String gameToken, int playerID, String sessionToken) throws NotLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPlayerWins", true);
                $out.write_string (gameToken);
                $out.write_long (playerID);
                $out.write_string (sessionToken);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:GameIDL/NotLoggedInException:1.0"))
                    throw NotLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPlayerWins (gameToken, playerID, sessionToken        );
            } finally {
                _releaseReply ($in);
            }
  } // getPlayerWins

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GameIDL/GameService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "GameIDL._GameServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GameServiceStub
