package Server_Java.idls.GameIDL;


/**
* GameIDL/AlreadyGuessedLetterException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Tuesday, April 29, 2025 5:49:19 PM CST
*/

public final class AlreadyGuessedLetterException extends org.omg.CORBA.UserException
{

  public AlreadyGuessedLetterException ()
  {
    super(AlreadyGuessedLetterExceptionHelper.id());
  } // ctor


  public AlreadyGuessedLetterException (String $reason)
  {
    super(AlreadyGuessedLetterExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyGuessedLetterException
