package Server_Java.idls.GameIDL;

/**
* Server_Java.idls.GameIDL/AlreadyGuessedLetterExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Wednesday, April 30, 2025 12:17:55 AM CST
*/

public final class AlreadyGuessedLetterExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Java.idls.GameIDL.AlreadyGuessedLetterException value = null;

  public AlreadyGuessedLetterExceptionHolder ()
  {
  }

  public AlreadyGuessedLetterExceptionHolder (Server_Java.idls.GameIDL.AlreadyGuessedLetterException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Java.idls.GameIDL.AlreadyGuessedLetterExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Java.idls.GameIDL.AlreadyGuessedLetterExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Java.idls.GameIDL.AlreadyGuessedLetterExceptionHelper.type ();
  }

}
