package Server_Java.idls.GameIDL;


/**
* Server_Java.idls.GameIDL/AlreadyGuessedLetterException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Wednesday, April 30, 2025 12:17:55 AM CST
*/

public final class AlreadyGuessedLetterException extends org.omg.CORBA.UserException
{

  public AlreadyGuessedLetterException ()
  {
    super(AlreadyGuessedLetterExceptionHelper.id());
  } // ctor


  public AlreadyGuessedLetterException (String $reason)
  {
    super(AlreadyGuessedLetterExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AlreadyGuessedLetterException
