package Server_Java.idls.GameIDL;

/**
* GameIDL/AlreadyGuessedLetterExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Tuesday, April 29, 2025 5:49:19 PM CST
*/

public final class AlreadyGuessedLetterExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AlreadyGuessedLetterException value = null;

  public AlreadyGuessedLetterExceptionHolder ()
  {
  }

  public AlreadyGuessedLetterExceptionHolder (AlreadyGuessedLetterException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AlreadyGuessedLetterExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AlreadyGuessedLetterExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AlreadyGuessedLetterExceptionHelper.type ();
  }

}
