package Server_Java.idls.GameIDL;

/**
* GameIDL/AlreadyLoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Tuesday, April 29, 2025 5:49:19 PM CST
*/


//
public final class AlreadyLoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AlreadyLoggedInException value = null;

  public AlreadyLoggedInExceptionHolder ()
  {
  }

  public AlreadyLoggedInExceptionHolder (AlreadyLoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AlreadyLoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AlreadyLoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AlreadyLoggedInExceptionHelper.type ();
  }

}
