package Server_Java.idls.GameIDL;


import Server_Java.idls.PlayerCallBackIDL.GameCallBackService;

/**
* GameIDL/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Tuesday, April 29, 2025 5:49:19 PM CST
*/


//
public interface GameServiceOperations 
{

  // ������ Player Authentication & Info ��������������������������������������������������������������
  String getDisplayName (int playerID, String sessionToken) throws NotLoggedInException;
  String[] getLeaderboards (int playerID, String sessionToken) throws NotLoggedInException;

  // ������ Settings Retrieval ����������������������������������������������������������������������������������
  void getSetting (String key, org.omg.CORBA.StringHolder value, String sessionToken) throws NotLoggedInException;

  // ������ Lobby Management ��������������������������������������������������������������������������������������
  String joinLobby (int playerID, String sessionToken) throws NotLoggedInException;
  String getLobbyStatus (String sessionToken) throws NotLoggedInException, GameTimeOutException, NotEnoughPlayersException;
  int getNumberOfPlayersJoined (int playerID, String sessionToken) throws NotLoggedInException;
  int startGame (int playerID, String sessionToken) throws NotEnoughPlayersException;

  // ������ Register the client's callback servant here ��������������������������������
  void registerCallBack (int playerID, String gameToken, String sessionToken, GameCallBackService cb) throws NotLoggedInException;

  // ������ Game and Round Management ��������������������������������������������������������������������
  int startRound (String gameToken, int roundNumber, int playerID, String sessionToken) throws GameNotFoundException, NotLoggedInException;
  String getRandomWord (String gameToken, int roundNumber, int playerID, String sessionToken) throws GameNotFoundException, NotLoggedInException;

  // ������ Letter Guessing ��������������������������������������������������������������������������������������
  int[] guessLetter (String gameToken, int playerID, String sessionToken, char letter) throws MaxAttemptsReachedException, GameNotFoundException, AlreadyGuessedLetterException, NotLoggedInException;

  // ������ Game and Round Results ����������������������������������������������������������������������
  String getRoundWinner (String gameToken, int playerID, String sessionToken) throws NotLoggedInException;
  String getGameWinner (String gameToken, int playerID, String sessionToken) throws NotLoggedInException;
  int getPlayerWins (String gameToken, int playerID, String sessionToken) throws NotLoggedInException;
} // interface GameServiceOperations
