package Server_Java.idls.GameIDL;

/**
* Server_Java.idls.GameIDL/GameTimeOutExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Wednesday, April 30, 2025 12:17:55 AM CST
*/

public final class GameTimeOutExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Java.idls.GameIDL.GameTimeOutException value = null;

  public GameTimeOutExceptionHolder ()
  {
  }

  public GameTimeOutExceptionHolder (Server_Java.idls.GameIDL.GameTimeOutException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Java.idls.GameIDL.GameTimeOutExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Java.idls.GameIDL.GameTimeOutExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Java.idls.GameIDL.GameTimeOutExceptionHelper.type ();
  }

}
