package Server_Java.idls.GameIDL;


/**
* GameIDL/GameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Tuesday, April 29, 2025 5:49:19 PM CST
*/


//
public interface GameService extends GameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface GameService
