package Server_Java.idls.GameIDL;

/**
* GameIDL/GameTimeOutExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Tuesday, April 29, 2025 5:49:19 PM CST
*/

public final class GameTimeOutExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameTimeOutException value = null;

  public GameTimeOutExceptionHolder ()
  {
  }

  public GameTimeOutExceptionHolder (GameTimeOutException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameTimeOutExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameTimeOutExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameTimeOutExceptionHelper.type ();
  }

}
