package Server_Java.idls.GameIDL;


/**
* Server_Java.idls.GameIDL/GameNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Wednesday, April 30, 2025 12:17:55 AM CST
*/

public final class GameNotFoundException extends org.omg.CORBA.UserException
{

  public GameNotFoundException ()
  {
    super(GameNotFoundExceptionHelper.id());
  } // ctor


  public GameNotFoundException (String $reason)
  {
    super(GameNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class GameNotFoundException
