package Server_Java.idls.GameIDL;


/**
* GameIDL/GameNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Tuesday, April 29, 2025 5:49:19 PM CST
*/

public final class GameNotFoundException extends org.omg.CORBA.UserException
{

  public GameNotFoundException ()
  {
    super(GameNotFoundExceptionHelper.id());
  } // ctor


  public GameNotFoundException (String $reason)
  {
    super(GameNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class GameNotFoundException
