package Server_Java.idls.GameIDL;


/**
* Server_Java.idls.GameIDL/GameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Wednesday, April 30, 2025 12:17:55 AM CST
*/


//
public interface GameService extends GameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameService
