package Server_Java.idls.GameIDL;


/**
* Server_Java.idls.GameIDL/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Wednesday, April 30, 2025 12:17:55 AM CST
*/


//
public interface GameServiceOperations 
{

  // ������ Player Authentication & Info ��������������������������������������������������������������
  String getDisplayName (int playerID, String sessionToken) throws Server_Java.idls.GameIDL.NotLoggedInException;
  String[] getLeaderboards (int playerID, String sessionToken) throws Server_Java.idls.GameIDL.NotLoggedInException;

  // ������ Settings Retrieval ����������������������������������������������������������������������������������
  void getSetting (String key, org.omg.CORBA.StringHolder value, String sessionToken) throws Server_Java.idls.GameIDL.NotLoggedInException;

  // ������ Lobby Management ��������������������������������������������������������������������������������������
  String joinLobby (int playerID, String sessionToken) throws Server_Java.idls.GameIDL.NotLoggedInException;
  void leaveLobby (int playerID, String gameToken, String sessionToken) throws Server_Java.idls.GameIDL.NotLoggedInException;

  // ������ Waiting-room callback registration ��������������������������������������������������
  void registerWaitingRoomCallback (int playerID, String gameToken, String sessionToken, Server_Java.idls.PlayerCallBackIDL.WaitingRoomGameCallbackService cb) throws Server_Java.idls.GameIDL.NotLoggedInException;
  String getLobbyStatus (String sessionToken) throws Server_Java.idls.GameIDL.NotLoggedInException, Server_Java.idls.GameIDL.GameTimeOutException, Server_Java.idls.GameIDL.NotEnoughPlayersException;
  int getNumberOfPlayersJoined (int playerID, String sessionToken) throws Server_Java.idls.GameIDL.NotLoggedInException;
  int startGame (int playerID, String sessionToken) throws Server_Java.idls.GameIDL.NotEnoughPlayersException;

  // ������ Register the client's callback servant here ��������������������������������
  void registerCallBack (int playerID, String gameToken, String sessionToken, Server_Java.idls.PlayerCallBackIDL.GameCallBackService cb) throws Server_Java.idls.GameIDL.NotLoggedInException;

  // ������ Game and Round Management ��������������������������������������������������������������������
  int startRound (String gameToken, int roundNumber, int playerID, String sessionToken) throws Server_Java.idls.GameIDL.GameNotFoundException, Server_Java.idls.GameIDL.NotLoggedInException;
  String getRandomWord (String gameToken, int roundNumber, int playerID, String sessionToken) throws Server_Java.idls.GameIDL.GameNotFoundException, Server_Java.idls.GameIDL.NotLoggedInException;

  // ������ Letter Guessing ��������������������������������������������������������������������������������������
  int[] guessLetter (String gameToken, int playerID, String sessionToken, char letter) throws Server_Java.idls.GameIDL.MaxAttemptsReachedException, Server_Java.idls.GameIDL.GameNotFoundException, Server_Java.idls.GameIDL.AlreadyGuessedLetterException, Server_Java.idls.GameIDL.NotLoggedInException;

  // ������ Game and Round Results ����������������������������������������������������������������������
  String getRoundWinner (String gameToken, int playerID, String sessionToken) throws Server_Java.idls.GameIDL.NotLoggedInException;
  String getGameWinner (String gameToken, int playerID, String sessionToken) throws Server_Java.idls.GameIDL.NotLoggedInException;
  int getPlayerWins (String gameToken, int playerID, String sessionToken) throws Server_Java.idls.GameIDL.NotLoggedInException;
} // interface GameServiceOperations
