package Server_Java.idls.GameIDL;

/**
* GameIDL/MaxAttemptsReachedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Tuesday, April 29, 2025 5:49:19 PM CST
*/

public final class MaxAttemptsReachedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public MaxAttemptsReachedException value = null;

  public MaxAttemptsReachedExceptionHolder ()
  {
  }

  public MaxAttemptsReachedExceptionHolder (MaxAttemptsReachedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MaxAttemptsReachedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MaxAttemptsReachedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MaxAttemptsReachedExceptionHelper.type ();
  }

}
