package Server_Java.idls.GameIDL;


/**
* Server_Java.idls.GameIDL/MaxAttemptsReachedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Wednesday, April 30, 2025 12:17:55 AM CST
*/

public final class MaxAttemptsReachedException extends org.omg.CORBA.UserException
{

  public MaxAttemptsReachedException ()
  {
    super(MaxAttemptsReachedExceptionHelper.id());
  } // ctor


  public MaxAttemptsReachedException (String $reason)
  {
    super(MaxAttemptsReachedExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class MaxAttemptsReachedException
