package Server_Java.idls.GameIDL;


/**
* GameIDL/MaxAttemptsReachedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Tuesday, April 29, 2025 5:49:19 PM CST
*/

public final class MaxAttemptsReachedException extends org.omg.CORBA.UserException
{

  public MaxAttemptsReachedException ()
  {
    super(MaxAttemptsReachedExceptionHelper.id());
  } // ctor


  public MaxAttemptsReachedException (String $reason)
  {
    super(MaxAttemptsReachedExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class MaxAttemptsReachedException
