package Server_Java.idls.GameIDL;


/**
* GameIDL/NotEnoughPlayersException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Tuesday, April 29, 2025 5:49:19 PM CST
*/

public final class NotEnoughPlayersException extends org.omg.CORBA.UserException
{

  public NotEnoughPlayersException ()
  {
    super(NotEnoughPlayersExceptionHelper.id());
  } // ctor


  public NotEnoughPlayersException (String $reason)
  {
    super(NotEnoughPlayersExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NotEnoughPlayersException
