package Server_Java.idls.GameIDL;


/**
* Server_Java.idls.GameIDL/NotEnoughPlayersException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Game.idl
* Wednesday, April 30, 2025 12:17:55 AM CST
*/

public final class NotEnoughPlayersException extends org.omg.CORBA.UserException
{

  public NotEnoughPlayersException ()
  {
    super(NotEnoughPlayersExceptionHelper.id());
  } // ctor


  public NotEnoughPlayersException (String $reason)
  {
    super(NotEnoughPlayersExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NotEnoughPlayersException
