package Server_Java.idls.AdminIDL;

/**
* AdminIDL/AccountCurrentlyActiveExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Tuesday, April 29, 2025 5:49:05 PM CST
*/

public final class AccountCurrentlyActiveExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public AccountCurrentlyActiveException value = null;

  public AccountCurrentlyActiveExceptionHolder ()
  {
  }

  public AccountCurrentlyActiveExceptionHolder (AccountCurrentlyActiveException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AccountCurrentlyActiveExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AccountCurrentlyActiveExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AccountCurrentlyActiveExceptionHelper.type ();
  }

}
