package Server_Java.idls.AdminIDL;

/**
* Server_Java.idls.AdminIDL/AccountNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Wednesday, April 30, 2025 12:18:12 AM CST
*/

public final class AccountNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Java.idls.AdminIDL.AccountNotFoundException value = null;

  public AccountNotFoundExceptionHolder ()
  {
  }

  public AccountNotFoundExceptionHolder (Server_Java.idls.AdminIDL.AccountNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Java.idls.AdminIDL.AccountNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Java.idls.AdminIDL.AccountNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Java.idls.AdminIDL.AccountNotFoundExceptionHelper.type ();
  }

}
