package Server_Java.idls.AdminIDL;


/**
* Server_Java.idls.AdminIDL/AccountNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Wednesday, April 30, 2025 12:18:12 AM CST
*/

public final class AccountNotFoundException extends org.omg.CORBA.UserException
{

  public AccountNotFoundException ()
  {
    super(AccountNotFoundExceptionHelper.id());
  } // ctor


  public AccountNotFoundException (String $reason)
  {
    super(AccountNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccountNotFoundException
