package Server_Java.idls.AdminIDL;


/**
* AdminIDL/AccountCurrentlyActiveException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Tuesday, April 29, 2025 5:49:05 PM CST
*/

public final class AccountCurrentlyActiveException extends org.omg.CORBA.UserException
{

  public AccountCurrentlyActiveException ()
  {
    super(AccountCurrentlyActiveExceptionHelper.id());
  } // ctor


  public AccountCurrentlyActiveException (String $reason)
  {
    super(AccountCurrentlyActiveExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccountCurrentlyActiveException
