package Server_Java.idls.AdminIDL;


/**
* AdminIDL/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Tuesday, April 29, 2025 5:49:05 PM CST
*/

public interface AdminServiceOperations 
{

  // Create a new player account
  void createPlayer (String username, String password, String sessionToken, int adminID) throws AccountExistsException, NotLoggedInException;

  // Modify existing player's password
  void modifyPlayer (int playerID, String newPassword, String sessionToken, int adminID) throws AccountNotFoundException, ExistingPasswordException, NotLoggedInException;

  // Delete player account
  void deletePlayer (int playerID, String sessionToken, int adminID) throws AccountNotFoundException, AccountCurrentlyActiveException, NotLoggedInException;

  // Search for a player by username
  String searchPlayer (String username, String sessionToken, int adminID) throws NotLoggedInException, PlayerNotFoundException;

  // Change waiting time before game starts
  void modifyWaitingTime (int waitTime, String sessionToken, int adminID) throws NotLoggedInException;

  // Change time duration for each round
  void modifyRoundDuration (int roundTime, String sessionToken, int adminID) throws NotLoggedInException;
} // interface AdminServiceOperations
