package Server_Java.idls.AdminIDL;


/**
* AdminIDL/AdminService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Tuesday, April 29, 2025 5:49:05 PM CST
*/

public interface AdminService extends AdminServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface AdminService
