package Server_Java.idls.AdminIDL;


/**
* Server_Java.idls.AdminIDL/AdminService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Wednesday, April 30, 2025 12:18:12 AM CST
*/

public interface AdminService extends AdminServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminService
