package Server_Java.idls.AdminIDL;


/**
* Server_Java.idls.AdminIDL/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Wednesday, April 30, 2025 12:18:12 AM CST
*/

public interface AdminServiceOperations 
{

  // Create a new player account
  void createPlayer (String username, String password, String sessionToken, int adminID) throws Server_Java.idls.AdminIDL.AccountExistsException, Server_Java.idls.AdminIDL.NotLoggedInException;

  // Modify existing player's password
  void modifyPlayer (int playerID, String newPassword, String sessionToken, int adminID) throws Server_Java.idls.AdminIDL.AccountNotFoundException, Server_Java.idls.AdminIDL.ExistingPasswordException, Server_Java.idls.AdminIDL.NotLoggedInException;

  // Delete player account
  void deletePlayer (int playerID, String sessionToken, int adminID) throws Server_Java.idls.AdminIDL.AccountNotFoundException, Server_Java.idls.AdminIDL.AccountCurrentlyActiveException, Server_Java.idls.AdminIDL.NotLoggedInException;

  // Search for a player by username
  String searchPlayer (String username, String sessionToken, int adminID) throws Server_Java.idls.AdminIDL.NotLoggedInException, Server_Java.idls.AdminIDL.PlayerNotFoundException;

  // Change waiting time before game starts
  void modifyWaitingTime (int waitTime, String sessionToken, int adminID) throws Server_Java.idls.AdminIDL.NotLoggedInException;

  // Change time duration for each round
  void modifyRoundDuration (int roundTime, String sessionToken, int adminID) throws Server_Java.idls.AdminIDL.NotLoggedInException;
} // interface AdminServiceOperations
