package Server_Java.idls.AdminIDL;

/**
* Server_Java.idls.AdminIDL/ExistingPasswordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Wednesday, April 30, 2025 12:18:12 AM CST
*/

public final class ExistingPasswordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Java.idls.AdminIDL.ExistingPasswordException value = null;

  public ExistingPasswordExceptionHolder ()
  {
  }

  public ExistingPasswordExceptionHolder (Server_Java.idls.AdminIDL.ExistingPasswordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Java.idls.AdminIDL.ExistingPasswordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Java.idls.AdminIDL.ExistingPasswordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Java.idls.AdminIDL.ExistingPasswordExceptionHelper.type ();
  }

}
