package Server_Java.idls.AdminIDL;


/**
* Server_Java.idls.AdminIDL/ExistingPasswordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Wednesday, April 30, 2025 12:18:12 AM CST
*/

public final class ExistingPasswordException extends org.omg.CORBA.UserException
{

  public ExistingPasswordException ()
  {
    super(ExistingPasswordExceptionHelper.id());
  } // ctor


  public ExistingPasswordException (String $reason)
  {
    super(ExistingPasswordExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class ExistingPasswordException
