package Server_Java.idls.AdminIDL;

/**
* AdminIDL/ExistingPasswordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Tuesday, April 29, 2025 5:49:05 PM CST
*/

public final class ExistingPasswordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ExistingPasswordException value = null;

  public ExistingPasswordExceptionHolder ()
  {
  }

  public ExistingPasswordExceptionHolder (ExistingPasswordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ExistingPasswordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ExistingPasswordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ExistingPasswordExceptionHelper.type ();
  }

}
