package Server_Java.idls.AdminIDL;


/**
* Server_Java.idls.AdminIDL/PlayerNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Wednesday, April 30, 2025 12:18:12 AM CST
*/

public final class PlayerNotFoundException extends org.omg.CORBA.UserException
{

  public PlayerNotFoundException ()
  {
    super(PlayerNotFoundExceptionHelper.id());
  } // ctor


  public PlayerNotFoundException (String $reason)
  {
    super(PlayerNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class PlayerNotFoundException
