package Server_Java.idls.AdminIDL;


/**
* AdminIDL/PlayerNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Admin.idl
* Tuesday, April 29, 2025 5:49:05 PM CST
*/

public final class PlayerNotFoundException extends org.omg.CORBA.UserException
{

  public PlayerNotFoundException ()
  {
    super(PlayerNotFoundExceptionHelper.id());
  } // ctor


  public PlayerNotFoundException (String $reason)
  {
    super(PlayerNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class PlayerNotFoundException
